package com.guyghost.wakeve.ui.equipment

import com.guyghost.wakeve.models.EquipmentCategory
import com.guyghost.wakeve.models.ItemStatus
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class EquipmentCopyTest {

    @Test
    fun equipmentScreenCopyUsesSpecificLabels() {
        assertEquals("Liste d'équipement", equipmentScreenTitle())
        assertEquals("Retour", equipmentBackContentDescription())
        assertEquals("Préparer automatiquement une liste d'équipement", equipmentAutoGenerateContentDescription())
        assertEquals("Aucun commentaire équipement", equipmentCommentContentDescription(0))
        assertEquals("1 commentaire équipement", equipmentCommentContentDescription(1))
        assertEquals("4 commentaires équipement", equipmentCommentContentDescription(4))
        assertEquals("Ajouter un équipement", equipmentAddContentDescription())
        assertEquals("Tous", equipmentAllStatusesLabel())
        assertEquals("Aucun équipement ajouté", equipmentEmptyListMessage())
        assertEquals("Aucun équipement avec ce statut", equipmentEmptyFilteredMessage())
        assertEquals("Préparer une liste", equipmentPrepareListActionLabel())
    }

    @Test
    fun equipmentDialogCopyExplainsRequiredFieldsAndOwnership() {
        assertEquals("Ajouter un équipement", equipmentItemDialogTitle(isNewItem = true))
        assertEquals("Modifier l'équipement", equipmentItemDialogTitle(isNewItem = false))
        assertEquals("Nom requis", equipmentItemNameLabel())
        assertEquals("Quantité requise", equipmentItemQuantityLabel())
        assertEquals("Coût partagé (€)", equipmentItemSharedCostLabel())
        assertEquals("Responsable", equipmentAssignedToLabel())
        assertEquals("Non assigné", equipmentUnassignedLabel())
        assertEquals("Ajouter", equipmentItemDialogConfirmLabel(isNewItem = true))
        assertEquals("Modifier", equipmentItemDialogConfirmLabel(isNewItem = false))
    }

    @Test
    fun equipmentStatusCopyIsActionableForGroupChecklist() {
        assertEquals("Requis", equipmentStatusLabel(ItemStatus.NEEDED))
        assertEquals("Assigné", equipmentStatusLabel(ItemStatus.ASSIGNED))
        assertEquals("Confirmé", equipmentStatusLabel(ItemStatus.CONFIRMED))
        assertEquals("Prêt", equipmentStatusLabel(ItemStatus.PACKED))
        assertEquals("Annulé", equipmentStatusLabel(ItemStatus.CANCELLED))
        assertFalse(equipmentStatusLabel(ItemStatus.PACKED).contains("Emballé", ignoreCase = true))

        ItemStatus.entries.forEach { status ->
            assertFalse(equipmentStatusLabel(status).contains(status.name))
        }
    }

    @Test
    fun equipmentCategoryCopyHidesEnumNames() {
        assertEquals("Camping", equipmentCategoryLabel(EquipmentCategory.CAMPING))
        assertEquals("Sport", equipmentCategoryLabel(EquipmentCategory.SPORTS))
        assertEquals("Cuisine", equipmentCategoryLabel(EquipmentCategory.COOKING))
        assertEquals("Électronique", equipmentCategoryLabel(EquipmentCategory.ELECTRONICS))
        assertEquals("Sécurité", equipmentCategoryLabel(EquipmentCategory.SAFETY))
        assertEquals("Autre", equipmentCategoryLabel(EquipmentCategory.OTHER))

        EquipmentCategory.entries.forEach { category ->
            assertFalse(equipmentCategoryLabel(category).contains(category.name))
        }
    }

    @Test
    fun equipmentProgressAndDeletionCopyAreClear() {
        assertEquals("Progression", equipmentProgressTitle())
        assertEquals("2 / 5 équipements prêts (40%)", equipmentProgressLabel(2, 5, 40))
        assertEquals("Supprimer l'équipement ?", equipmentDeleteItemTitle())
        assertEquals("Supprimer « Tente » de la liste d'équipement ?", equipmentDeleteItemMessage("Tente"))
        assertEquals("Assigner « Tente »", equipmentAssignDialogTitle("Tente"))
        assertEquals("Préparer une liste d'équipement", equipmentAutoGenerateTitle())
        assertTrue(equipmentAutoGenerateDescription().contains("adaptée au groupe", ignoreCase = true))
    }
}
