package com.guyghost.wakeve.ui.meal

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.outlined.Comment
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Cake
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.DinnerDining
import androidx.compose.material.icons.filled.Egg
import androidx.compose.material.icons.filled.LocalBar
import androidx.compose.material.icons.filled.LocationOn
import androidx.compose.material.icons.filled.LunchDining
import androidx.compose.material.icons.filled.Person
import androidx.compose.material.icons.filled.Restaurant
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.AssistChip
import androidx.compose.material3.AssistChipDefaults
import androidx.compose.material3.Badge
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FilterChip
import androidx.compose.material3.FloatingActionButton
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.res.pluralStringResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.guyghost.wakeve.comment.CommentRepository
import com.guyghost.wakeve.R
import com.guyghost.wakeve.meal.MealPlanner
import com.guyghost.wakeve.meal.MealRepository
import com.guyghost.wakeve.models.CommentSection
import com.guyghost.wakeve.models.DailyMealSchedule
import com.guyghost.wakeve.models.Meal
import com.guyghost.wakeve.models.MealRequest
import com.guyghost.wakeve.models.MealStatus
import com.guyghost.wakeve.models.MealType
import com.guyghost.wakeve.models.ParticipantDietaryRestriction
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.time.format.FormatStyle

/**
 * Meal Planning Screen
 * 
 * Features:
 * - List meals grouped by date (Daily Schedule)
 * - Filter by type and status
 * - Add/Edit/Delete meals
 * - Auto-generate meal plan
 * - Manage dietary restrictions
 * - Assign responsibilities
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MealPlanningScreen(
    eventId: String,
    mealRepository: MealRepository,
    commentRepository: CommentRepository,
    onNavigateBack: () -> Unit,
    onNavigateToComments: (eventId: String, section: CommentSection, sectionItemId: String?) -> Unit
) {
    var dailySchedules by remember { mutableStateOf<List<DailyMealSchedule>>(emptyList()) }
    var dietaryRestrictions by remember { mutableStateOf<List<ParticipantDietaryRestriction>>(emptyList()) }
    var selectedType by remember { mutableStateOf<MealType?>(null) }
    var selectedStatus by remember { mutableStateOf<MealStatus?>(null) }
    var showAddMealDialog by remember { mutableStateOf(false) }
    var showAutoGenerateDialog by remember { mutableStateOf(false) }
    var mealToEdit by remember { mutableStateOf<Meal?>(null) }
    var mealToDelete by remember { mutableStateOf<Meal?>(null) }
    var showDietaryRestrictionsDialog by remember { mutableStateOf(false) }
    var commentCount by remember { mutableIntStateOf(0) }
    
    // Load data
    fun loadData() {
        dailySchedules = mealRepository.getDailyMealSchedule(eventId)
        dietaryRestrictions = mealRepository.getDietaryRestrictionsByEventId(eventId)
        commentCount = commentRepository.countCommentsBySection(eventId, CommentSection.MEAL).toInt()
    }
    
    LaunchedEffect(eventId) {
        loadData()
    }
    
    // Flatten and filter meals
    val allMeals = dailySchedules.flatMap { it.meals }
    val filteredMeals = allMeals.filter { meal ->
        val typeMatch = selectedType == null || meal.type == selectedType
        val statusMatch = selectedStatus == null || meal.status == selectedStatus
        typeMatch && statusMatch
    }
    
    // Regroup filtered meals by date
    val filteredSchedules = MealPlanner.groupMealsByDate(filteredMeals)
    
    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.meal_screen_title)) },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, stringResource(R.string.a11y_meal_back))
                    }
                },
                actions = {
                    // Dietary restrictions button
                    val constraintsDescription = stringResource(
                        R.string.a11y_meal_open_constraints,
                        dietaryRestrictions.size
                    )
                    IconButton(
                        onClick = { showDietaryRestrictionsDialog = true },
                        modifier = Modifier.clearAndSetSemantics {
                            contentDescription = constraintsDescription
                        }
                    ) {
                        Badge(
                            containerColor = if (dietaryRestrictions.isNotEmpty()) 
                                MaterialTheme.colorScheme.error 
                            else 
                                MaterialTheme.colorScheme.surfaceVariant
                        ) {
                            Text(dietaryRestrictions.size.toString())
                        }
                    }
                    
                    // Auto-generate button
                    IconButton(onClick = { showAutoGenerateDialog = true }) {
                        Icon(Icons.Default.AutoAwesome, stringResource(R.string.a11y_meal_prepare_plan))
                    }

                    // Comments icon with badge
                    IconButton(onClick = {
                        onNavigateToComments(eventId, CommentSection.MEAL, null)
                    }) {
                        Box {
                            Icon(
                                Icons.AutoMirrored.Outlined.Comment,
                                contentDescription = pluralStringResource(
                                    R.plurals.a11y_meal_comments,
                                    commentCount,
                                    commentCount
                                )
                            )
                            if (commentCount > 0) {
                                Box(
                                    modifier = Modifier
                                        .size(16.dp)
                                        .background(
                                            color = MaterialTheme.colorScheme.error,
                                            shape = CircleShape
                                        )
                                        .align(Alignment.TopEnd),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Text(
                                        text = commentCount.toString(),
                                        style = MaterialTheme.typography.labelSmall,
                                        color = MaterialTheme.colorScheme.onError,
                                        fontWeight = FontWeight.Bold
                                    )
                                }
                            }
                        }
                    }
                }
            )
        },
        floatingActionButton = {
            FloatingActionButton(
                onClick = { showAddMealDialog = true }
            ) {
                Icon(Icons.Default.Add, stringResource(R.string.a11y_meal_add))
            }
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
        ) {
            // Summary card
            if (allMeals.isNotEmpty()) {
                MealSummaryCard(
                    meals = allMeals,
                    dietaryRestrictions = dietaryRestrictions
                )
            }
            
            // Filter chips
            MealFiltersRow(
                selectedType = selectedType,
                selectedStatus = selectedStatus,
                onTypeSelected = { selectedType = if (it == selectedType) null else it },
                onStatusSelected = { selectedStatus = if (it == selectedStatus) null else it }
            )
            
            // Meal list grouped by date
            if (filteredSchedules.isEmpty()) {
                // Empty state
                Box(
                    modifier = Modifier.fillMaxSize(),
                    contentAlignment = Alignment.Center
                ) {
                    Column(
                        horizontalAlignment = Alignment.CenterHorizontally,
                        verticalArrangement = Arrangement.spacedBy(16.dp)
                    ) {
                        Icon(
                            Icons.Default.Restaurant,
                            contentDescription = null,
                            modifier = Modifier.size(64.dp),
                            tint = MaterialTheme.colorScheme.primary
                        )
                        Text(
                            stringResource(R.string.meal_empty_title),
                            style = MaterialTheme.typography.titleLarge
                        )
                        Text(
                            stringResource(R.string.meal_empty_description),
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(8.dp)
                        ) {
                            Button(onClick = { showAutoGenerateDialog = true }) {
                                Icon(Icons.Default.AutoAwesome, contentDescription = null)
                                Spacer(Modifier.width(8.dp))
                                Text(stringResource(R.string.meal_action_generate))
                            }
                            OutlinedButton(onClick = { showAddMealDialog = true }) {
                                Icon(Icons.Default.Add, contentDescription = null)
                                Spacer(Modifier.width(8.dp))
                                Text(stringResource(R.string.meal_action_add))
                            }
                        }
                    }
                }
            } else {
                LazyColumn(
                    modifier = Modifier.fillMaxSize(),
                    contentPadding = PaddingValues(16.dp),
                    verticalArrangement = Arrangement.spacedBy(16.dp)
                ) {
                    filteredSchedules.forEach { schedule ->
                        item {
                            DailyScheduleSection(
                                schedule = schedule,
                                onMealClick = { mealToEdit = it },
                                onDeleteClick = { mealToDelete = it }
                            )
                        }
                    }
                }
            }
        }
    }
    
    // Dialogs
    if (showAddMealDialog) {
        AddEditMealDialog(
            meal = null,
            eventId = eventId,
            onDismiss = { showAddMealDialog = false },
            onSave = { request ->
                mealRepository.createMeal(request)
                loadData()
                showAddMealDialog = false
            }
        )
    }
    
    mealToEdit?.let { meal ->
        AddEditMealDialog(
            meal = meal,
            eventId = eventId,
            onDismiss = { mealToEdit = null },
            onSave = { request ->
                val updated = meal.copy(
                    type = request.type,
                    name = request.name,
                    date = request.date,
                    time = request.time,
                    location = request.location,
                    responsibleParticipantIds = request.responsibleParticipantIds,
                    estimatedCost = request.estimatedCost,
                    actualCost = request.actualCost,
                    servings = request.servings,
                    status = request.status,
                    notes = request.notes
                )
                mealRepository.updateMeal(updated)
                loadData()
                mealToEdit = null
            }
        )
    }
    
    mealToDelete?.let { meal ->
        AlertDialog(
            onDismissRequest = { mealToDelete = null },
            title = { Text(stringResource(R.string.meal_delete_title)) },
            text = { Text(stringResource(R.string.meal_delete_message, meal.name)) },
            confirmButton = {
                TextButton(
                    onClick = {
                        mealRepository.deleteMeal(meal.id)
                        loadData()
                        mealToDelete = null
                    },
                    colors = ButtonDefaults.textButtonColors(
                        contentColor = MaterialTheme.colorScheme.error
                    )
                ) {
                    Text(stringResource(R.string.meal_action_delete))
                }
            },
            dismissButton = {
                TextButton(onClick = { mealToDelete = null }) {
                    Text(stringResource(R.string.meal_action_cancel))
                }
            }
        )
    }
    
    if (showAutoGenerateDialog) {
        AutoGenerateMealsDialog(
            eventId = eventId,
            onDismiss = { showAutoGenerateDialog = false },
            onGenerate = { request ->
                val generatedMeals = MealPlanner.autoGenerateMeals(request)
                generatedMeals.forEach { meal ->
                    val mealRequest = MealRequest(
                        eventId = meal.eventId,
                        type = meal.type,
                        name = meal.name,
                        date = meal.date,
                        time = meal.time,
                        location = meal.location,
                        responsibleParticipantIds = meal.responsibleParticipantIds,
                        estimatedCost = meal.estimatedCost,
                        actualCost = meal.actualCost,
                        servings = meal.servings,
                        status = meal.status,
                        notes = meal.notes
                    )
                    mealRepository.createMeal(mealRequest)
                }
                loadData()
                showAutoGenerateDialog = false
            }
        )
    }
    
    if (showDietaryRestrictionsDialog) {
        DietaryRestrictionsDialog(
            eventId = eventId,
            restrictions = dietaryRestrictions,
            mealRepository = mealRepository,
            onDismiss = { 
                loadData()
                showDietaryRestrictionsDialog = false 
            }
        )
    }
}

/**
 * Summary card showing meal statistics
 */
@Composable
fun MealSummaryCard(
    meals: List<Meal>,
    dietaryRestrictions: List<ParticipantDietaryRestriction>
) {
    val summary = MealPlanner.generateMealSummary(meals)
    
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .padding(16.dp)
    ) {
        Column(
            modifier = Modifier.padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            Text(
                stringResource(R.string.meal_summary_title),
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
            )
            
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Column {
                    Text(
                        stringResource(R.string.meal_total_label),
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Text(
                        pluralStringResource(R.plurals.meal_count, summary.totalMeals, summary.totalMeals),
                        style = MaterialTheme.typography.titleLarge,
                        fontWeight = FontWeight.Bold
                    )
                }
                
                Column {
                    Text(
                        stringResource(R.string.meal_estimated_total_label),
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Text(
                        stringResource(R.string.meal_currency_amount, summary.totalEstimatedCost / 100.0),
                        style = MaterialTheme.typography.titleLarge,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.primary
                    )
                }
                
                Column {
                    Text(
                        stringResource(R.string.meal_completed_label),
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Text(
                        stringResource(R.string.meal_completed_ratio, summary.mealsCompleted, summary.totalMeals),
                        style = MaterialTheme.typography.titleLarge,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.tertiary
                    )
                }
            }
            
            if (dietaryRestrictions.isNotEmpty()) {
                HorizontalDivider()
                Text(
                    pluralStringResource(
                        R.plurals.meal_constraint_count,
                        dietaryRestrictions.size,
                        dietaryRestrictions.size
                    ),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.error
                )
            }
        }
    }
}

/**
 * Filter chips row
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MealFiltersRow(
    selectedType: MealType?,
    selectedStatus: MealStatus?,
    onTypeSelected: (MealType) -> Unit,
    onStatusSelected: (MealStatus) -> Unit
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp),
        verticalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        // Type filters
        Text(
            stringResource(R.string.meal_type_label),
            style = MaterialTheme.typography.labelMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )
        
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            MealType.entries.forEach { type ->
                val typeLabel = getMealTypeLabel(type)
                val selectedState = stringResource(if (selectedType == type) R.string.meal_selected_state else R.string.meal_unselected_state)
                val typeDescription = stringResource(
                    R.string.a11y_meal_filter_type,
                    typeLabel,
                    selectedState
                )
                FilterChip(
                    selected = selectedType == type,
                    onClick = { onTypeSelected(type) },
                    modifier = Modifier.clearAndSetSemantics {
                        contentDescription = typeDescription
                    },
                    label = { Text(typeLabel) }
                )
            }
        }
        
        // Status filters
        Text(
            stringResource(R.string.meal_status_label),
            style = MaterialTheme.typography.labelMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )
        
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            MealStatus.entries.forEach { status ->
                val statusLabel = getMealStatusLabel(status)
                val selectedState = stringResource(if (selectedStatus == status) R.string.meal_selected_state else R.string.meal_unselected_state)
                val statusDescription = stringResource(
                    R.string.a11y_meal_filter_status,
                    statusLabel,
                    selectedState
                )
                FilterChip(
                    selected = selectedStatus == status,
                    onClick = { onStatusSelected(status) },
                    modifier = Modifier.clearAndSetSemantics {
                        contentDescription = statusDescription
                    },
                    label = { Text(statusLabel) }
                )
            }
        }
    }
    
    Spacer(Modifier.height(8.dp))
}

/**
 * Daily schedule section (meals grouped by date)
 */
@Composable
fun DailyScheduleSection(
    schedule: DailyMealSchedule,
    onMealClick: (Meal) -> Unit,
    onDeleteClick: (Meal) -> Unit
) {
    Column(
        verticalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        // Date header
        val dateFormatter = DateTimeFormatter.ofLocalizedDate(FormatStyle.FULL)
            .withLocale(LocalConfiguration.current.locales[0])
        val formattedDate = try {
            LocalDate.parse(schedule.date).format(dateFormatter)
        } catch (e: Exception) {
            schedule.date
        }
        
        Text(
            formattedDate,
            style = MaterialTheme.typography.titleMedium,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.primary
        )
        
        // Meals for this date
        schedule.meals.sortedBy { it.time }.forEach { meal ->
            MealCard(
                meal = meal,
                onClick = { onMealClick(meal) },
                onDeleteClick = { onDeleteClick(meal) }
            )
        }
    }
}

/**
 * Individual meal card
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MealCard(
    meal: Meal,
    onClick: () -> Unit,
    onDeleteClick: () -> Unit
) {
    val statusLabel = getMealStatusLabel(meal.status)
    val openDescription = stringResource(R.string.a11y_meal_open, meal.name, statusLabel)
    val deleteDescription = stringResource(R.string.a11y_meal_delete, meal.name)
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .clickable(onClick = onClick)
            .clearAndSetSemantics {
                contentDescription = openDescription
            },
        colors = CardDefaults.cardColors(
            containerColor = when (meal.status) {
                MealStatus.COMPLETED -> MaterialTheme.colorScheme.tertiaryContainer
                MealStatus.IN_PROGRESS -> MaterialTheme.colorScheme.primaryContainer
                MealStatus.CANCELLED -> MaterialTheme.colorScheme.errorContainer
                else -> MaterialTheme.colorScheme.surfaceVariant
            }
        )
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column(
                modifier = Modifier.weight(1f),
                verticalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                // Time + Type badge
                Row(
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        meal.time,
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Bold
                    )
                    
                    AssistChip(
                        onClick = {},
                        label = { Text(getMealTypeLabel(meal.type)) },
                        leadingIcon = {
                            Icon(
                                getMealTypeIcon(meal.type),
                                contentDescription = null,
                                modifier = Modifier.size(16.dp)
                            )
                        }
                    )
                }
                
                // Meal name
                Text(
                    meal.name,
                    style = MaterialTheme.typography.bodyLarge
                )
                
                // Location
                meal.location?.let { location ->
                    Row(
                        horizontalArrangement = Arrangement.spacedBy(4.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            Icons.Default.LocationOn,
                            contentDescription = null,
                            modifier = Modifier.size(16.dp),
                            tint = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        Text(
                            location,
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }
                
                // Responsible + Servings + Cost
                Row(
                    horizontalArrangement = Arrangement.spacedBy(12.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    if (meal.responsibleParticipantIds.isNotEmpty()) {
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(4.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(
                                Icons.Default.Person,
                                contentDescription = null,
                                modifier = Modifier.size(14.dp),
                                tint = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                            Text(
                                pluralStringResource(
                                    R.plurals.meal_responsible_count,
                                    meal.responsibleParticipantIds.size,
                                    meal.responsibleParticipantIds.size
                                ),
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }
                    
                    Row(
                        horizontalArrangement = Arrangement.spacedBy(4.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            Icons.Default.Restaurant,
                            contentDescription = null,
                            modifier = Modifier.size(14.dp),
                            tint = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        Text(
                            pluralStringResource(R.plurals.meal_serving_count, meal.servings, meal.servings),
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                    
                    Text(
                        stringResource(R.string.meal_currency_amount, meal.estimatedCost / 100.0),
                        style = MaterialTheme.typography.bodySmall,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.primary
                    )
                }
                
                // Status badge
                AssistChip(
                    onClick = {},
                    label = { Text(statusLabel) },
                    colors = AssistChipDefaults.assistChipColors(
                        containerColor = when (meal.status) {
                            MealStatus.COMPLETED -> MaterialTheme.colorScheme.tertiary
                            MealStatus.IN_PROGRESS -> MaterialTheme.colorScheme.primary
                            MealStatus.CANCELLED -> MaterialTheme.colorScheme.error
                            else -> MaterialTheme.colorScheme.secondary
                        },
                        labelColor = when (meal.status) {
                            MealStatus.COMPLETED -> MaterialTheme.colorScheme.onTertiary
                            MealStatus.IN_PROGRESS -> MaterialTheme.colorScheme.onPrimary
                            MealStatus.CANCELLED -> MaterialTheme.colorScheme.onError
                            else -> MaterialTheme.colorScheme.onSecondary
                        }
                    )
                )
            }
            
            // Delete button
            IconButton(
                onClick = onDeleteClick,
                modifier = Modifier.clearAndSetSemantics {
                    contentDescription = deleteDescription
                }
            ) {
                Icon(
                    Icons.Default.Delete,
                    contentDescription = null,
                    tint = MaterialTheme.colorScheme.error
                )
            }
        }
    }
}

// Helper functions

@Composable
fun getMealTypeLabel(type: MealType): String = stringResource(when (type) {
    MealType.BREAKFAST -> R.string.meal_type_breakfast
    MealType.LUNCH -> R.string.meal_type_lunch
    MealType.DINNER -> R.string.meal_type_dinner
    MealType.SNACK -> R.string.meal_type_snack
    MealType.APERITIF -> R.string.meal_type_aperitif
})

fun getMealTypeIcon(type: MealType) = when (type) {
    MealType.BREAKFAST -> Icons.Default.Egg
    MealType.LUNCH -> Icons.Default.LunchDining
    MealType.DINNER -> Icons.Default.DinnerDining
    MealType.SNACK -> Icons.Default.Cake
    MealType.APERITIF -> Icons.Default.LocalBar
}

@Composable
fun getMealStatusLabel(status: MealStatus): String = stringResource(when (status) {
    MealStatus.PLANNED -> R.string.meal_status_planned
    MealStatus.ASSIGNED -> R.string.meal_status_assigned
    MealStatus.IN_PROGRESS -> R.string.meal_status_in_progress
    MealStatus.COMPLETED -> R.string.meal_status_completed
    MealStatus.CANCELLED -> R.string.meal_status_cancelled
})
