import SwiftUI
import Combine
import Shared

/**
 * AlbumViewModelSwiftUI - Simplified SwiftUI wrapper for Album management.
 * 
 * This class provides basic album management functionality using available types.
 * Note: AlbumRepository interface exists but lacks concrete implementation.
 * This wrapper uses Album_ type directly for basic operations.
 */
@MainActor
class AlbumViewModelSwiftUI: ObservableObject {
    // MARK: - Published Properties
    
    @Published var albums: [Album_] = []
    @Published var selectedAlbum: Album_? = nil
    @Published var isLoading: Bool = false
    @Published var errorMessage: String? = nil
    
    // MARK: - Properties
    
    private let eventId: String
    
    // MARK: - Initialization
    
    init(eventId: String) {
        self.eventId = eventId
        // Note: Full AlbumRepository implementation pending
        // For now, albums would need to be loaded via alternative means
    }
    
    // MARK: - Public Methods
    
    func loadAlbums() async {
        isLoading = true
        errorMessage = nil
        // TODO: Implement album loading when AlbumRepository has concrete implementation
        // For now, this is a placeholder
        isLoading = false
    }
    
    func createAlbum(name: String, description: String?, coverPhotoIndex: Int?) async -> Bool {
        isLoading = true
        errorMessage = nil
        
        let newAlbum = Album_(
            id: UUID().uuidString,
            eventId: eventId,
            name: name,
            coverPhotoId: nil,
            photoIds: [],
            createdAt: ISO8601DateFormatter().string(from: Date()),
            isAutoGenerated: false,
            updatedAt: nil
        )
        
        albums.append(newAlbum)
        isLoading = false
        return true
    }
    
    func deleteAlbum(_ album: Album_) async -> Bool {
        isLoading = true
        errorMessage = nil
        albums.removeAll { $0.id == album.id }
        isLoading = false
        return true
    }
    
    func getSmartAlbums() -> [Album_] {
        return albums.filter { $0.isAutoGenerated }
    }
    
    func getUserAlbums() -> [Album_] {
        return albums.filter { !$0.isAutoGenerated }
    }
}

// MARK: - Album Extensions

extension Album_ {
    var isSmartAlbum: Bool {
        return name.hasPrefix("smart_") || name.hasPrefix("Smart ")
    }
    
    var photoCount: Int {
        return photoIds.count
    }
}
