package com.guyghost.wakeve.repository

import com.guyghost.wakeve.models.Album

/**
 * Repository interface for managing photo albums.
 * Provides methods for creating, retrieving, updating, and deleting albums.
 */
interface AlbumRepository {
    
    /**
     * Creates a new album.
     *
     * @param album The album to create
     */
    suspend fun createAlbum(album: Album)
    
    /**
     * Gets all albums for a specific event.
     *
     * @param eventId The event ID (null for all albums)
     * @return List of albums sorted by creation date (newest first)
     */
    suspend fun getAlbums(eventId: String?): List<Album>
    
    /**
     * Gets an album by its ID.
     *
     * @param albumId The album ID
     * @return The album or null if not found
     */
    suspend fun getAlbum(albumId: String): Album?
    
    /**
     * Updates an album.
     *
     * @param album The album with updated values
     */
    suspend fun updateAlbum(album: Album)
    
    /**
     * Updates an album's name.
     *
     * @param albumId The album ID
     * @param name The new name
     */
    suspend fun updateAlbumName(albumId: String, name: String)
    
    /**
     * Updates an album's cover photo.
     *
     * @param albumId The album ID
     * @param coverPhotoId The new cover photo ID
     */
    suspend fun updateAlbumCover(albumId: String, coverPhotoId: String)
    
    /**
     * Deletes an album.
     *
     * @param albumId The album ID to delete
     */
    suspend fun deleteAlbum(albumId: String)
    
    /**
     * Adds a photo to an album.
     *
     * @param albumId The album ID
     * @param photoId The photo ID to add
     */
    suspend fun addPhotoToAlbum(albumId: String, photoId: String)
    
    /**
     * Removes a photo from an album.
     *
     * @param albumId The album ID
     * @param photoId The photo ID to remove
     */
    suspend fun removePhotoFromAlbum(albumId: String, photoId: String)
    
    /**
     * Gets all auto-generated albums.
     *
     * @return List of auto-generated albums
     */
    suspend fun getAutoGeneratedAlbums(): List<Album>
    
    /**
     * Gets all custom (user-created) albums.
     *
     * @return List of custom albums
     */
    suspend fun getCustomAlbums(): List<Album>
    
    /**
     * Searches albums by name.
     *
     * @param query The search query
     * @return List of matching albums
     */
    suspend fun searchAlbumsByName(query: String): List<Album>
}
