package com.guyghost.wakeve.ui.screens

import com.guyghost.wakeve.models.Album
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNull
import kotlin.test.assertTrue

class AlbumsCopyTest {

    @Test
    fun albumsTopLevelCopyUsesSpecificAccessibleLabels() {
        assertEquals("Albums", albumsScreenTitle())
        assertEquals("Rechercher des photos", albumSearchContentDescription())
        assertEquals("Créer un album", albumCreateContentDescription())
        assertEquals("Ajouter des photos", albumAddPhotosContentDescription())
        assertEquals("Retour", albumBackContentDescription())
        assertEquals("Partager", albumShareContentDescription())
        assertEquals("Supprimer", albumDeleteContentDescription())
        assertEquals("Fermer", albumCloseContentDescription())
        assertEquals("Rechercher des photos...", albumSearchPlaceholder())
    }

    @Test
    fun albumPhotoCountCopyHandlesPluralForms() {
        assertEquals("0 photo", albumPhotoCountLabel(0))
        assertEquals("1 photo", albumPhotoCountLabel(1))
        assertEquals("2 photos", albumPhotoCountLabel(2))
        assertEquals("Photos (2 photos)", albumPhotosSectionTitle(2))
        assertEquals("Album Week-end, 3 photos", albumCardContentDescription("Week-end", 3))
        assertEquals("Photo de couverture de l'album Week-end", albumCoverContentDescription("Week-end"))
    }

    @Test
    fun albumsAfterEventEmptyStatesExplainRetentionValue() {
        assertEquals("Aucun album", albumEmptyTitle())
        assertEquals("Aucune photo", albumEmptyPhotosTitle())
        assertTrue(albumEmptyDescription().contains("après l'événement", ignoreCase = true))
        assertTrue(albumEmptyPhotosDescription().contains("souvenirs", ignoreCase = true))
        assertTrue(albumEmptyPhotosDescription().contains("groupe", ignoreCase = true))
    }

    @Test
    fun albumCreateAndSearchCopyIsClear() {
        assertEquals("Nouvel album", albumCreateDialogTitle())
        assertEquals("Donnez un nom à votre album.", albumCreateDialogDescription())
        assertEquals("Nom de l'album", albumNameFieldLabel())
        assertEquals("Ex. Mariage de Sophie", albumNamePlaceholder())
        assertEquals("Créer", albumCreateActionLabel())
        assertEquals("Annuler", albumCancelActionLabel())
        assertEquals("Aucune photo trouvée", albumSearchEmptyMessage())
        assertFalse(albumNamePlaceholder().contains("Ex:", ignoreCase = true))
    }

    @Test
    fun albumPhotoSemanticsAreUsefulForScreenReaders() {
        assertEquals("Partage intelligent", albumSmartSharingTitle())
        assertEquals("Photo : sans légende", albumPhotoContentDescription(null))
        assertEquals("Photo : sans légende", albumPhotoContentDescription(""))
        assertEquals("Photo : Arrivée du groupe", albumPhotoContentDescription("Arrivée du groupe"))
        assertEquals("Photo favorite", albumFavoriteContentDescription())
    }

    @Test
    fun albumShareSummarySelectsUsefulNonEmptyAlbum() {
        val summary = albumShareSummary(
            listOf(
                album(id = "empty", name = "Vide", photoIds = emptyList(), isAutoGenerated = true, coverPhotoId = "cover"),
                album(id = "manual", name = "Tout", photoIds = listOf("p1", "p2", "p3", "p4")),
                album(id = "auto", name = "Best of", photoIds = listOf("a1", "a2"), isAutoGenerated = true, coverPhotoId = "a1")
            )
        )

        assertEquals("auto", summary?.albumId)
        assertEquals("À partager maintenant : Best of", summary?.title)
        assertEquals(
            "2 photos dans cette sélection automatique pour relancer le groupe après l'événement.",
            summary?.body
        )
        assertEquals(listOf("a1", "a2"), summary?.photoIds)
        assertEquals("Partager", albumShareNowActionLabel())
    }

    @Test
    fun albumShareSummaryIsHiddenWhenThereAreNoPhotos() {
        assertNull(
            albumShareSummary(
                listOf(album(id = "empty", name = "Vide", photoIds = emptyList()))
            )
        )
        assertEquals("À partager maintenant : Soirée", albumShareSummaryTitle("Soirée"))
        assertEquals(
            "1 photo dans cet album prêt pour relancer le groupe après l'événement.",
            albumShareSummaryBody(photoCount = 1, isAutoGenerated = false)
        )
    }

    private fun album(
        id: String,
        name: String,
        photoIds: List<String>,
        isAutoGenerated: Boolean = false,
        coverPhotoId: String? = null
    ): Album =
        Album(
            id = id,
            eventId = "event-1",
            name = name,
            coverPhotoId = coverPhotoId,
            photoIds = photoIds,
            createdAt = "2026-06-01T08:00:00Z",
            isAutoGenerated = isAutoGenerated,
            updatedAt = "2026-06-02T08:00:00Z"
        )
}
