package com.guyghost.wakeve.ui.screens

import com.guyghost.wakeve.models.Album
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull

class AlbumsCopyTest {

    @Test
    fun albumShareSummarySelectsUsefulNonEmptyAlbum() {
        val summary = albumShareSummary(
            listOf(
                album(id = "empty", name = "Vide", photoIds = emptyList(), isAutoGenerated = true, coverPhotoId = "cover"),
                album(id = "manual", name = "Tout", photoIds = listOf("p1", "p2", "p3", "p4")),
                album(id = "auto", name = "Best of", photoIds = listOf("a1", "a2"), isAutoGenerated = true, coverPhotoId = "a1")
            )
        )

        assertEquals("auto", summary?.albumId)
        assertEquals("Best of", summary?.albumName)
        assertEquals(2, summary?.photoCount)
        assertEquals(true, summary?.isAutoGenerated)
        assertEquals(listOf("a1", "a2"), summary?.photoIds)
    }

    @Test
    fun albumShareSummaryIsHiddenWhenThereAreNoPhotos() {
        assertNull(
            albumShareSummary(
                listOf(album(id = "empty", name = "Vide", photoIds = emptyList()))
            )
        )
    }

    private fun album(
        id: String,
        name: String,
        photoIds: List<String>,
        isAutoGenerated: Boolean = false,
        coverPhotoId: String? = null
    ): Album =
        Album(
            id = id,
            eventId = "event-1",
            name = name,
            coverPhotoId = coverPhotoId,
            photoIds = photoIds,
            createdAt = "2026-06-01T08:00:00Z",
            isAutoGenerated = isAutoGenerated,
            updatedAt = "2026-06-02T08:00:00Z"
        )
}
