import Foundation
import SwiftUI

/// AI Suggestion Models - Swift equivalents to Kotlin models for AI predictive features
///
/// These models will eventually be synced with Kotlin/Native interop but serve
/// as the Swift source of truth for UI development and testing.
///
/// Matches Kotlin models in shared/src/commonMain/kotlin/com/guyghost/wakeve/domain/model/ai/

// MARK: - AI Badge Models

/// Represents an AI-generated badge with display properties and metadata
struct AIBadge: Identifiable, Codable, Hashable {
    let id: String
    let type: AIBadgeType
    let displayName: String
    let icon: String
    let colorHex: String
    let tooltip: String?
    
    /// Computed SwiftUI Color from hex string
    var color: Color {
        Color(hex: colorHex) ?? .primary
    }
    
    /// Default badges for common AI scenarios
    static let defaults: [AIBadgeType: AIBadge] = [
        .aiSuggestion: AIBadge(
            id: "ai-suggestion",
            type: .aiSuggestion,
            displayName: "AI Suggestion",
            icon: "🤖",
            colorHex: "#6200EE",
            tooltip: "This recommendation is generated by our AI system"
        ),
        .highConfidence: AIBadge(
            id: "high-confidence",
            type: .highConfidence,
            displayName: "High Confidence",
            icon: "🎯",
            colorHex: "#4CAF50",
            tooltip: "This recommendation has a high confidence score"
        ),
        .mediumConfidence: AIBadge(
            id: "medium-confidence",
            type: .mediumConfidence,
            displayName: "Medium Confidence",
            icon: "📊",
            colorHex: "#FF9800",
            tooltip: "This recommendation has a moderate confidence score"
        ),
        .personalized: AIBadge(
            id: "personalized",
            type: .personalized,
            displayName: "Personalized",
            icon: "✨",
            colorHex: "#9C27B0",
            tooltip: "This recommendation is personalized for you"
        ),
        .popularChoice: AIBadge(
            id: "popular-choice",
            type: .popularChoice,
            displayName: "Popular",
            icon: "🔥",
            colorHex: "#F44336",
            tooltip: "This is a popular choice among users"
        ),
        .seasonal: AIBadge(
            id: "seasonal",
            type: .seasonal,
            displayName: "Seasonal",
            icon: "🍂",
            colorHex: "#795548",
            tooltip: "This recommendation is seasonal"
        )
    ]
    
    /// Factory method to create badge from type
    static func from(type: AIBadgeType) -> AIBadge {
        defaults[type] ?? AIBadge(
            id: type.rawValue.lowercased(),
            type: type,
            displayName: type.rawValue.replacingOccurrences(of: "_", with: " "),
            icon: "🤖",
            colorHex: "#6200EE",
            tooltip: "AI generated suggestion"
        )
    }
}

/// Types of AI badges for different recommendation contexts
enum AIBadgeType: String, Codable, CaseIterable, Hashable {
    case aiSuggestion = "AI_SUGGESTION"
    case highConfidence = "HIGH_CONFIDENCE"
    case mediumConfidence = "MEDIUM_CONFIDENCE"
    case personalized = "PERSONALIZED"
    case popularChoice = "POPULAR_CHOICE"
    case seasonal = "SEASONAL"
    
    /// Human-readable display name
    var displayName: String {
        switch self {
        case .aiSuggestion:
            return "AI Suggestion"
        case .highConfidence:
            return "High Confidence"
        case .mediumConfidence:
            return "Medium Confidence"
        case .personalized:
            return "Personalized"
        case .popularChoice:
            return "Popular Choice"
        case .seasonal:
            return "Seasonal"
        }
    }
    
    /// Default icon for this badge type
    var defaultIcon: String {
        switch self {
        case .aiSuggestion:
            return "🤖"
        case .highConfidence:
            return "🎯"
        case .mediumConfidence:
            return "📊"
        case .personalized:
            return "✨"
        case .popularChoice:
            return "🔥"
        case .seasonal:
            return "🍂"
        }
    }
    
    /// Default color hex for this badge type
    var defaultColorHex: String {
        switch self {
        case .aiSuggestion:
            return "#6200EE"
        case .highConfidence:
            return "#4CAF50"
        case .mediumConfidence:
            return "#FF9800"
        case .personalized:
            return "#9C27B0"
        case .popularChoice:
            return "#F44336"
        case .seasonal:
            return "#795548"
        }
    }
}

// MARK: - AI Metadata

/// Metadata about AI predictions including confidence and source information
struct AIMetadata: Codable, Hashable {
    let confidenceScore: Double
    let predictionSource: PredictionSource
    let modelVersion: String
    let featuresUsed: [String: String]
    let createdAt: String
    
    /// Human-readable confidence level
    var confidenceLevel: ConfidenceLevel {
        switch confidenceScore {
        case 0.9...1.0:
            return .veryHigh
        case 0.7..<0.9:
            return .high
        case 0.5..<0.7:
            return .medium
        case 0.3..<0.5:
            return .low
        default:
            return .veryLow
        }
    }
    
    /// Formatted confidence percentage
    var confidencePercentage: String {
        "\(Int(confidenceScore * 100))%"
    }
    
    /// Convenience for creating mock metadata
    static func mock(
        confidenceScore: Double = 0.85,
        predictionSource: PredictionSource = .mlModel,
        modelVersion: String = "2.1.0",
        featuresUsed: [String: String] = [:]
    ) -> AIMetadata {
        AIMetadata(
            confidenceScore: confidenceScore,
            predictionSource: predictionSource,
            modelVersion: modelVersion,
            featuresUsed: featuresUsed,
            createdAt: ISO8601DateFormatter().string(from: Date())
        )
    }
}

/// Confidence level enum for display purposes
enum ConfidenceLevel: String, Codable, CaseIterable {
    case veryHigh = "Very High"
    case high = "High"
    case medium = "Medium"
    case low = "Low"
    case veryLow = "Very Low"
    
    /// Color based on confidence level
    var color: Color {
        switch self {
        case .veryHigh:
            return .green
        case .high:
            return .blue
        case .medium:
            return .orange
        case .low:
            return .red
        case .veryLow:
            return .gray
        }
    }
}

/// Source of AI prediction
enum PredictionSource: String, Codable, Hashable {
    case mlModel = "ML_MODEL"
    case heuristic = "HEURISTIC"
    case hybrid = "HYBRID"
    
    /// Human-readable display name
    var displayName: String {
        switch self {
        case .mlModel:
            return "ML Model"
        case .heuristic:
            return "Heuristic"
        case .hybrid:
            return "Hybrid"
        }
    }
    
    /// Icon for this prediction source
    var icon: String {
        switch self {
        case .mlModel:
            return "brain.head.profile"
        case .heuristic:
            return "lightbulb"
        case .hybrid:
            return "sparkles"
        }
    }
}

// MARK: - Generic AI Suggestion Wrapper

/// Generic wrapper for AI suggestions containing data and metadata
struct AISuggestion<T: Hashable>: Identifiable, Hashable {
    let id: String
    let data: T
    let metadata: AIMetadata
    
    /// Initialize with data and metadata
    init(id: String = UUID().uuidString, data: T, metadata: AIMetadata) {
        self.id = id
        self.data = data
        self.metadata = metadata
    }
}

// MARK: - Date Recommendation Models

/// AI recommendation for event date/time
struct DateRecommendation: Hashable, Identifiable {
    var id: String { "\(date)-\(timeSlot)" }
    let date: String
    let timeSlot: String
    let reasoning: String?
    let alternativeDates: [String]?
    
    /// Create mock date recommendation
    static func mock(
        date: String = "Saturday, January 15, 2026",
        timeSlot: String = "Afternoon (2PM - 6PM)",
        reasoning: String? = "Best weather forecast and highest participant availability",
        alternativeDates: [String]? = nil
    ) -> DateRecommendation {
        DateRecommendation(
            date: date,
            timeSlot: timeSlot,
            reasoning: reasoning,
            alternativeDates: alternativeDates
        )
    }
}

// MARK: - Location Recommendation Models

/// AI recommendation for event location
struct LocationRecommendation: Hashable, Identifiable {
    var id: String { name }
    let name: String
    let type: LocationType
    let address: String
    let reasoning: String?
    let priceEstimate: String?
    
    enum LocationType: String, Hashable {
        case venue = "Venue"
        case restaurant = "Restaurant"
        case outdoor = "Outdoor"
        case virtual = "Virtual"
    }
    
    /// Create mock location recommendation
    static func mock(
        name: String = "Sunset Beach",
        type: LocationType = .outdoor,
        address: String = "123 Beach Road, Malibu",
        reasoning: String? = "Perfect weather and scenic views",
        priceEstimate: String? = "Free"
    ) -> LocationRecommendation {
        LocationRecommendation(
            name: name,
            type: type,
            address: address,
            reasoning: reasoning,
            priceEstimate: priceEstimate
        )
    }
}

// MARK: - Previews

#Preview("AI Badge Models") {
    VStack(spacing: 16) {
        ForEach(AIBadgeType.allCases, id: \.self) { type in
            let badge = AIBadge.from(type: type)
            HStack {
                Text(badge.icon)
                    .font(.title2)
                VStack(alignment: .leading) {
                    Text(badge.displayName)
                        .font(.headline)
                    Text(badge.tooltip ?? "")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
                Spacer()
            }
            .padding()
            .glassCard()
        }
    }
    .padding()
}

#Preview("AIMetadata Confidence Levels") {
    VStack(spacing: 16) {
        ForEach([0.95, 0.75, 0.55, 0.35], id: \.self) { score in
            let metadata = AIMetadata.mock(confidenceScore: score)
            HStack {
                Text(metadata.confidencePercentage)
                    .font(.headline)
                    .foregroundColor(metadata.confidenceLevel.color)
                Text(metadata.predictionSource.displayName)
                    .font(.caption)
                Spacer()
            }
            .padding()
            .glassCard()
        }
    }
    .padding()
}
