#!/usr/bin/env bash
# Captures public DNS, legal/support URL, AASA, and backend health evidence
# for the App Store AS-14 live URL gate.

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
. "$PROJECT_DIR/scripts/lib/report-sanitization.sh"
OUTPUT_DIR="$PROJECT_DIR/docs/app-store-live-url-aasa"
ALLOW_FAILURES=false
TIMEOUT_SECONDS=12
IOS_BUNDLE_ID="${IOS_BUNDLE_ID:-com.guyghost.wakeve}"

usage() {
    cat <<'USAGE'
Usage: ./scripts/capture-app-store-live-url-aasa.sh [--allow-failures] [--output-dir DIR] [--timeout SECONDS]

Environment:
  APPLE_TEAM_ID     Real 10-character Apple Developer Team ID for AASA app ID checks.
  IOS_BUNDLE_ID     iOS bundle ID, defaults to com.guyghost.wakeve.

Options:
  --allow-failures  Write the evidence report but exit 0 when live checks fail.
  --output-dir DIR  Directory for the generated Markdown report.
  --timeout N       curl timeout in seconds, defaults to 12.
USAGE
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --allow-failures)
            ALLOW_FAILURES=true
            shift
            ;;
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --timeout)
            TIMEOUT_SECONDS="$2"
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

mkdir -p "$OUTPUT_DIR"

timestamp="$(date -u '+%Y-%m-%dT%H-%M-%SZ')"
report="$OUTPUT_DIR/live-url-aasa-$timestamp.md"
failures=0

dns_hosts=(
    "wakeve.app"
    "api.wakeve.app"
)

legal_urls=(
    "https://wakeve.app/privacy"
    "https://wakeve.app/support"
    "https://wakeve.app/terms"
    "https://wakeve.app/third-party-notices"
    "https://api.wakeve.app/health"
)

app_urls=(
    "https://wakeve.app/app"
    "https://wakeve.app/app/login"
    "https://wakeve.app/app/dashboard"
    "https://wakeve.app/app/create"
    "https://wakeve.app/app/events"
)

redirect_urls=(
    "https://wakeve.app/dashboard|/app/dashboard"
    "https://wakeve.app/login|/app/login"
    "https://wakeve.app/create|/app/create"
    "https://wakeve.app/events|/app/events"
)

aasa_urls=(
    "https://wakeve.app/.well-known/apple-app-site-association"
    "https://wakeve.app/apple-app-site-association"
)

append_command_output() {
    local command_label="$1"
    shift

    {
        printf '```bash\n'
        printf '%s\n' "$command_label"
        printf '```\n\n'
        printf '```text\n'
    } >> "$report"

    set +e
    "$@" >> "$report" 2>&1
    local status=$?
    set -e

    {
        printf '\n[exit=%s]\n' "$status"
        printf '```\n\n'
    } >> "$report"

    return "$status"
}

curl_headers() {
    local url="$1"
    /usr/bin/curl -I --max-time "$TIMEOUT_SECONDS" "$url"
}

curl_body() {
    local url="$1"
    /usr/bin/curl -i --max-time "$TIMEOUT_SECONDS" "$url"
}

http_status() {
    local url="$1"
    /usr/bin/curl -sS -o /dev/null -w '%{http_code}' --max-time "$TIMEOUT_SECONDS" "$url"
}

normalize_report_whitespace() {
    sanitize_report_file "$report"
}

{
    printf '# App Store Live URL And AASA Capture\n\n'
    printf 'Date: %s\n\n' "$timestamp"
    printf 'Status: PENDING\n\n'
    printf 'This report is generated by `./scripts/capture-app-store-live-url-aasa.sh`. It is evidence for AS-14 only; it does not complete the App Store live URL gate unless every required check passes with the real production domains and Apple Team ID.\n\n'
    printf '| Field | Value |\n'
    printf '| --- | --- |\n'
    printf '| Apple Team ID | `%s` |\n' "${APPLE_TEAM_ID:-unset}"
    printf '| iOS Bundle ID | `%s` |\n' "$IOS_BUNDLE_ID"
    printf '| Timeout | `%ss` |\n\n' "$TIMEOUT_SECONDS"
} > "$report"

{
    printf '## DNS\n\n'
} >> "$report"

for host in "${dns_hosts[@]}"; do
    if append_command_output "dig +short $host" dig +short "$host"; then
        if ! dig +short "$host" | grep -q .; then
            failures=$((failures + 1))
        fi
    else
        failures=$((failures + 1))
    fi
done

{
    printf '## HTTP Reachability\n\n'
} >> "$report"

for url in "${legal_urls[@]}"; do
    if ! append_command_output "curl -I --max-time $TIMEOUT_SECONDS $url" curl_headers "$url"; then
        failures=$((failures + 1))
    fi
done

{
    printf '## App Shell And Redirects\n\n'
} >> "$report"

for url in "${app_urls[@]}"; do
    if ! append_command_output "curl -I --max-time $TIMEOUT_SECONDS $url" curl_headers "$url"; then
        failures=$((failures + 1))
        continue
    fi

    status="$(http_status "$url" || true)"
    if ! printf '%s' "$status" | grep -Eq '^(2|3)[0-9][0-9]$'; then
        failures=$((failures + 1))
    fi
done

for entry in "${redirect_urls[@]}"; do
    url="${entry%%|*}"
    expected_location="${entry#*|}"
    tmp_headers="$(mktemp)"

    {
        printf '```bash\n'
        printf 'curl -I --max-time %s %s\n' "$TIMEOUT_SECONDS" "$url"
        printf '```\n\n'
        printf '```text\n'
    } >> "$report"

    set +e
    /usr/bin/curl -I --max-time "$TIMEOUT_SECONDS" "$url" > "$tmp_headers" 2>&1
    status=$?
    set -e

    cat "$tmp_headers" >> "$report"
    {
        printf '\n[exit=%s]\n' "$status"
        printf '```\n\n'
    } >> "$report"

    if [ "$status" -ne 0 ] || ! grep -Eiq '^location:[[:space:]]*(https://wakeve\.app)?'"$expected_location"'([[:space:]]|$)' "$tmp_headers"; then
        failures=$((failures + 1))
    fi

    rm -f "$tmp_headers"
done

{
    printf '## AASA Content\n\n'
} >> "$report"

for url in "${aasa_urls[@]}"; do
    tmp_body="$(mktemp)"
    tmp_headers="$(mktemp)"

    {
        printf '```bash\n'
        printf 'curl -i --max-time %s %s\n' "$TIMEOUT_SECONDS" "$url"
        printf '```\n\n'
        printf '```text\n'
    } >> "$report"

    set +e
    /usr/bin/curl -i --max-time "$TIMEOUT_SECONDS" -D "$tmp_headers" "$url" -o "$tmp_body" >> "$report" 2>&1
    status=$?
    set -e

    if [ "$status" -eq 0 ]; then
        cat "$tmp_headers" >> "$report"
        printf '\n' >> "$report"
        cat "$tmp_body" >> "$report"
    fi

    {
        printf '\n[exit=%s]\n' "$status"
        printf '```\n\n'
    } >> "$report"

    if [ "$status" -ne 0 ]; then
        failures=$((failures + 1))
    else
        if ! grep -qi '^content-type:[[:space:]]*application/json' "$tmp_headers"; then
            failures=$((failures + 1))
        fi
        if ! ruby -rjson -e 'JSON.parse(File.read(ARGV.fetch(0)))' "$tmp_body" >/dev/null 2>&1; then
            failures=$((failures + 1))
        fi
        if [ -n "${APPLE_TEAM_ID:-}" ]; then
            if ! grep -Fq "${APPLE_TEAM_ID}.${IOS_BUNDLE_ID}" "$tmp_body"; then
                failures=$((failures + 1))
            fi
        else
            failures=$((failures + 1))
        fi
        for path in '/event/*' '/poll/*' '/meeting/*' '/invite/*'; do
            if ! grep -Fq "$path" "$tmp_body"; then
                failures=$((failures + 1))
            fi
        done
    fi

    rm -f "$tmp_body" "$tmp_headers"
done

{
    printf '## Summary\n\n'
    if [ "$failures" -eq 0 ]; then
        printf 'Result: PASS. Public DNS, HTTPS, AASA, and backend health checks passed for the captured environment.\n'
    else
        printf 'Result: FAIL. %s required live URL/AASA checks failed or could not be validated.\n' "$failures"
    fi
} >> "$report"

normalize_report_whitespace

printf 'Wrote %s\n' "$report"

if [ "$failures" -ne 0 ] && [ "$ALLOW_FAILURES" != true ]; then
    exit 1
fi
