package com.guyghost.wakeve.viewmodel

import com.guyghost.wakeve.access.ParticipantRepositoryRecord
import com.guyghost.wakeve.models.Album
import com.guyghost.wakeve.models.AlbumFilterParams
import com.guyghost.wakeve.models.Event
import com.guyghost.wakeve.models.EventStatus
import com.guyghost.wakeve.models.Photo
import com.guyghost.wakeve.models.Poll
import com.guyghost.wakeve.models.Vote
import com.guyghost.wakeve.repository.AlbumRepository
import com.guyghost.wakeve.repository.AlbumUpdateParams
import com.guyghost.wakeve.repository.EventRepositoryInterface
import com.guyghost.wakeve.repository.OrderBy
import com.guyghost.wakeve.repository.PhotoRepository
import com.guyghost.wakeve.services.SmartSharingService
import com.guyghost.wakeve.workflow.WorkflowOutboxRecord
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.flow.take
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.After
import org.junit.Before
import org.junit.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertIs

@OptIn(ExperimentalCoroutinesApi::class)
class AlbumViewModelErrorMessageTest {
    private val dispatcher = UnconfinedTestDispatcher()

    @Before
    fun setUp() {
        Dispatchers.setMain(dispatcher)
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }

    @Test
    fun albumsViewModelUsesGenericMessageWhenAlbumLoadThrows() = runTest {
        val albumRepository = FakeAlbumRepository().apply {
            getAlbumsException = sensitiveFailure()
        }

        val viewModel = albumsViewModel(albumRepository)
        advanceUntilIdle()

        assertEquals(albumListFailureMessage(), viewModel.uiState.value.error)
        assertDoesNotExposeSensitiveDetails(viewModel.uiState.value.error.orEmpty())
    }

    @Test
    fun albumsViewModelUsesGenericMessageWhenPhotoSearchThrows() = runTest {
        val photoRepository = FakePhotoRepository().apply {
            searchException = sensitiveFailure()
        }
        val viewModel = albumsViewModel(photoRepository = photoRepository)
        advanceUntilIdle()

        viewModel.updateSearchQuery("budget")
        advanceUntilIdle()

        assertEquals(albumSearchFailureMessage(), viewModel.uiState.value.error)
        assertDoesNotExposeSensitiveDetails(viewModel.uiState.value.error.orEmpty())
    }

    @Test
    fun albumsViewModelUsesGenericMessageWhenAlbumCreateThrows() = runTest {
        val albumRepository = FakeAlbumRepository().apply {
            createAlbumException = sensitiveFailure()
        }
        val viewModel = albumsViewModel(albumRepository)
        advanceUntilIdle()

        viewModel.createNewAlbum("After party")
        advanceUntilIdle()

        assertEquals(albumCreateFailureMessage(), viewModel.uiState.value.error)
        assertDoesNotExposeSensitiveDetails(viewModel.uiState.value.error.orEmpty())
    }

    @Test
    fun albumsViewModelLoadsEventScopedAlbumsAndPostEventPhotoFollowUp() = runTest {
        val albumRepository = FakeAlbumRepository().apply {
            albums = listOf(
                testAlbum("event-album").copy(
                    eventId = "event-1",
                    name = "Best of",
                    photoIds = listOf("p1", "p2"),
                    isAutoGenerated = true
                ),
                testAlbum("other-album").copy(
                    eventId = "event-2",
                    name = "Autre",
                    photoIds = listOf("x1")
                )
            )
        }
        val viewModel = albumsViewModel(albumRepository)
        advanceUntilIdle()

        viewModel.loadAlbumsForEvent("event-1")
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertEquals(listOf(null, "event-1"), albumRepository.requestedEventIds)
        assertEquals("event-1", state.eventId)
        assertEquals(listOf("event-album"), state.albums.map { it.id })
        assertEquals("Photos a partager", state.postEventPhotoFollowUp?.title)
        assertEquals("2 photos pretes pour le groupe", state.postEventPhotoFollowUp?.subtitle)
    }

    @Test
    fun albumsViewModelCreatesNewAlbumsInsideCurrentEventScope() = runTest {
        val albumRepository = FakeAlbumRepository()
        val viewModel = albumsViewModel(albumRepository)
        advanceUntilIdle()

        viewModel.loadAlbumsForEvent("event-1")
        advanceUntilIdle()
        viewModel.createNewAlbum("Souvenirs", photoIds = listOf("p1"))
        advanceUntilIdle()

        assertEquals("event-1", albumRepository.createdAlbums.single().eventId)
        assertEquals("Souvenirs", albumRepository.createdAlbums.single().name)
    }

    @Test
    fun smartAlbumsViewModelUsesGenericMessageWhenLoadReturnsFailure() = runTest {
        val albumRepository = FakeAlbumRepository().apply {
            getSmartAlbumsResult = Result.failure(sensitiveFailure())
        }

        val viewModel = SmartAlbumsViewModel(albumRepository)
        advanceUntilIdle()

        val errorState = assertIs<SmartAlbumsUiState.Error>(viewModel.uiState.value)
        assertEquals(albumListFailureMessage(), errorState.message)
        assertDoesNotExposeSensitiveDetails(errorState.message)
    }

    @Test
    fun smartAlbumsViewModelUsesGenericMessageWhenSearchReturnsFailure() = runTest {
        val albumRepository = FakeAlbumRepository().apply {
            searchAlbumsResult = Result.failure(sensitiveFailure())
        }
        val viewModel = SmartAlbumsViewModel(albumRepository)
        advanceUntilIdle()

        viewModel.searchAlbums("secret")
        advanceUntilIdle()

        val errorState = assertIs<SmartAlbumsUiState.Error>(viewModel.uiState.value)
        assertEquals(albumSearchFailureMessage(), errorState.message)
        assertDoesNotExposeSensitiveDetails(errorState.message)
    }

    @Test
    fun smartAlbumsViewModelUsesGenericMessageWhenCreateReturnsFailure() = runTest {
        val albumRepository = FakeAlbumRepository().apply {
            createSmartAlbumResult = Result.failure(sensitiveFailure())
        }
        val viewModel = SmartAlbumsViewModel(albumRepository)
        advanceUntilIdle()

        val effects = mutableListOf<SmartAlbumsSideEffect>()
        backgroundScope.launch(UnconfinedTestDispatcher(testScheduler)) {
            viewModel.sideEffect.take(1).toList(effects)
        }
        viewModel.createAlbum("Shared photos")
        advanceUntilIdle()

        val message = assertIs<SmartAlbumsSideEffect.ShowMessage>(effects.single()).message
        assertEquals(albumCreateFailureMessage(), message)
        assertDoesNotExposeSensitiveDetails(message)
    }

    @Test
    fun albumFailureHelpersUseStableSafeCopy() {
        val messages = listOf(
            albumListFailureMessage(),
            albumSearchFailureMessage(),
            albumDetailFailureMessage(),
            albumCreateFailureMessage(),
            albumUpdateFailureMessage(),
            albumDeleteFailureMessage(),
            albumCoverUpdateFailureMessage(),
            albumFavoriteUpdateFailureMessage(),
            albumAddPhotosFailureMessage(),
            albumRemovePhotosFailureMessage(),
            albumSharingSuggestionFailureMessage()
        )

        assertEquals(messages.size, messages.distinct().size)
        messages.forEach { message ->
            assertFalse(message.isBlank())
            assertDoesNotExposeSensitiveDetails(message)
        }
    }

    private fun albumsViewModel(
        albumRepository: FakeAlbumRepository = FakeAlbumRepository(),
        photoRepository: FakePhotoRepository = FakePhotoRepository()
    ): AlbumsViewModel {
        val eventRepository = FakeEventRepository()
        return AlbumsViewModel(
            albumRepository = albumRepository,
            photoRepository = photoRepository,
            eventRepository = eventRepository,
            smartSharingService = SmartSharingService(
                photoRepository = photoRepository,
                eventRepository = eventRepository,
                albumRepository = albumRepository
            )
        )
    }

    private fun sensitiveFailure(): IllegalStateException =
        IllegalStateException(
            "SQL constraint failed for secret@example.com token=SECRET http://internal.local/debug"
        )

    private fun assertDoesNotExposeSensitiveDetails(message: String) {
        listOf(
            "secret@example.com",
            "SECRET",
            "SQL constraint",
            "http://internal.local",
            "token="
        ).forEach { sensitiveValue ->
            assertFalse(
                message.contains(sensitiveValue, ignoreCase = true),
                "Message should not expose `$sensitiveValue`: $message"
            )
        }
    }

    private class FakeAlbumRepository : AlbumRepository {
        var getAlbumsException: Throwable? = null
        var createAlbumException: Throwable? = null
        var albums: List<Album> = emptyList()
        val requestedEventIds = mutableListOf<String?>()
        val createdAlbums = mutableListOf<Album>()
        var getSmartAlbumsResult: Result<List<Album>> = Result.success(emptyList())
        var searchAlbumsResult: Result<List<Album>> = Result.success(emptyList())
        var createSmartAlbumResult: Result<Album> = Result.success(testAlbum("created"))

        override suspend fun createAlbum(album: Album) {
            createAlbumException?.let { throw it }
            createdAlbums.add(album)
        }

        override suspend fun getAlbums(eventId: String?): List<Album> {
            requestedEventIds.add(eventId)
            getAlbumsException?.let { throw it }
            return eventId?.let { id -> albums.filter { it.eventId == id } } ?: albums
        }

        override suspend fun getAlbumSimple(albumId: String): Album? = null
        override suspend fun updateAlbum(album: Album) = Unit
        override suspend fun updateAlbumName(albumId: String, name: String) = Unit
        override suspend fun updateAlbumCover(albumId: String, coverPhotoId: String) = Unit
        override suspend fun deleteAlbumSimple(albumId: String) = Unit
        override suspend fun addPhotoToAlbum(albumId: String, photoId: String) = Unit
        override suspend fun removePhotoFromAlbum(albumId: String, photoId: String) = Unit
        override suspend fun getAlbums(params: AlbumFilterParams): Result<List<Album>> = getSmartAlbumsResult
        override suspend fun getAlbum(albumId: String): Result<Album?> = Result.success(null)
        override suspend fun createSmartAlbum(
            name: String,
            coverUri: String?,
            tags: List<String>,
            isFavorite: Boolean
        ): Result<Album> = createSmartAlbumResult

        override suspend fun updateAlbum(albumId: String, updates: AlbumUpdateParams): Result<Album> =
            Result.success(testAlbum(albumId))

        override suspend fun deleteAlbum(albumId: String): Result<Unit> = Result.success(Unit)
        override suspend fun toggleFavorite(albumId: String): Result<Album> = Result.success(testAlbum(albumId))
        override suspend fun addPhotosToAlbum(albumId: String, photoIds: List<String>): Result<Album> =
            Result.success(testAlbum(albumId))

        override suspend fun removePhotosFromAlbum(albumId: String, photoIds: List<String>): Result<Album> =
            Result.success(testAlbum(albumId))

        override suspend fun addTagsToAlbum(albumId: String, tags: List<String>): Result<Album> =
            Result.success(testAlbum(albumId))

        override suspend fun removeTagsFromAlbum(albumId: String, tags: List<String>): Result<Album> =
            Result.success(testAlbum(albumId))

        override suspend fun getAutoGeneratedAlbums(): Result<List<Album>> = Result.success(emptyList())
        override suspend fun getCustomAlbums(): Result<List<Album>> = Result.success(emptyList())
        override suspend fun getFavoriteAlbums(): Result<List<Album>> = Result.success(emptyList())
        override suspend fun getRecentAlbums(days: Int): Result<List<Album>> = Result.success(emptyList())
        override suspend fun searchAlbums(query: String): Result<List<Album>> = searchAlbumsResult
        override suspend fun getAlbumsByTags(tags: List<String>, matchAll: Boolean): Result<List<Album>> =
            Result.success(emptyList())

        override suspend fun getAlbumsByDateRange(startDate: String, endDate: String): Result<List<Album>> =
            Result.success(emptyList())

        override suspend fun getAlbumsContainingPhotos(photoIds: List<String>): Result<List<Album>> =
            Result.success(emptyList())
    }

    private class FakePhotoRepository : PhotoRepository {
        var searchException: Throwable? = null

        override suspend fun getPhoto(photoId: String): Photo? = null
        override suspend fun getPhotosByEvent(eventId: String): List<Photo> = emptyList()
        override suspend fun getAllPhotos(): List<Photo> = emptyList()
        override suspend fun savePhoto(photo: Photo) = Unit
        override suspend fun updatePhotoCaption(photoId: String, caption: String?) = Unit
        override suspend fun updatePhotoWithTags(
            photoId: String,
            faces: List<com.guyghost.wakeve.models.FaceDetection>,
            tags: List<com.guyghost.wakeve.models.PhotoTag>
        ) = Unit

        override suspend fun addTagsToPhoto(
            photoId: String,
            tags: List<com.guyghost.wakeve.models.PhotoTag>
        ) = Unit

        override suspend fun removeTagFromPhoto(photoId: String, tagId: String) = Unit
        override suspend fun addPhotoToAlbum(photoId: String, albumId: String) = Unit
        override suspend fun removePhotoFromAlbum(photoId: String, albumId: String) = Unit
        override suspend fun searchByQuery(query: String): List<Photo> {
            searchException?.let { throw it }
            return emptyList()
        }

        override suspend fun getPhotosByMinConfidence(minConfidence: Double): List<Photo> = emptyList()
        override suspend fun getPhotosWithFaces(): List<Photo> = emptyList()
        override suspend fun getPhotosByIds(ids: List<String>): List<Photo> = emptyList()
        override suspend fun deletePhoto(photoId: String) = Unit
        override suspend fun setFavorite(photoId: String, isFavorite: Boolean) = Unit
    }

    private class FakeEventRepository : EventRepositoryInterface {
        override suspend fun createEvent(event: Event): Result<Event> = Result.success(event)
        override fun getEvent(id: String): Event? = null
        override fun getPoll(eventId: String): Poll? = null
        override suspend fun addParticipant(eventId: String, participantId: String): Result<Boolean> = Result.success(true)
        override fun getParticipants(eventId: String): List<String>? = emptyList()
        override fun getParticipantRecords(eventId: String): List<ParticipantRepositoryRecord>? = emptyList()
        override suspend fun addVote(
            eventId: String,
            participantId: String,
            slotId: String,
            vote: Vote
        ): Result<Boolean> = Result.success(true)

        override suspend fun updateEvent(event: Event): Result<Event> = Result.success(event)
        override suspend fun updateEventStatus(id: String, status: EventStatus, finalDate: String?): Result<Boolean> =
            Result.success(true)

        override suspend fun confirmEventDate(
            eventId: String,
            slotId: String,
            confirmedByOrganizerId: String
        ): Result<Boolean> = Result.success(true)

        override suspend fun queueWorkflowOutbox(record: WorkflowOutboxRecord): Result<Boolean> = Result.success(true)
        override fun getWorkflowOutbox(eventId: String): List<WorkflowOutboxRecord> = emptyList()
        override suspend fun saveEvent(event: Event): Result<Event> = Result.success(event)
        override suspend fun deleteEvent(eventId: String): Result<Unit> = Result.success(Unit)
        override fun isDeadlinePassed(deadline: String): Boolean = false
        override fun isOrganizer(eventId: String, userId: String): Boolean = false
        override fun canModifyEvent(eventId: String, userId: String): Boolean = false
        override fun getAllEvents(): List<Event> = emptyList()
        override fun getEventsPaginated(page: Int, pageSize: Int, orderBy: OrderBy): Flow<List<Event>> =
            flowOf(emptyList())
    }
}

private fun testAlbum(id: String): Album =
    Album(
        id = id,
        eventId = null,
        name = "Album $id",
        coverPhotoId = null,
        photoIds = emptyList(),
        createdAt = "2026-06-20T10:00:00Z",
        isAutoGenerated = false
    )
