package com.guyghost.wakeve.models

/**
 * Represents a photo album that can be auto-generated or manually created.
 * Albums organize photos by events, moments, or custom criteria.
 *
 * @property id Unique album identifier
 * @property eventId Associated event ID (null for custom albums spanning multiple events)
 * @property name Display name (e.g., "Mariage de Sophie", "Summer 2025")
 * @property coverPhotoId ID of the cover photo (first photo or user-selected)
 * @property photoIds List of photo IDs in this album
 * @property createdAt ISO 8601 timestamp
 * @property isAutoGenerated True if created automatically by the system
 * @property updatedAt Last modification timestamp
 */
data class Album(
    val id: String,
    val eventId: String?,
    val name: String,
    val coverPhotoId: String?,
    val photoIds: List<String>,
    val createdAt: String,
    val isAutoGenerated: Boolean = false,
    val updatedAt: String? = null
)

/**
 * Extension to check if an album is empty.
 */
fun Album.isEmpty(): Boolean = photoIds.isEmpty()

/**
 * Extension to get the number of photos in an album.
 */
fun Album.photoCount(): Int = photoIds.size
