import { assign, setup } from 'xstate'

export type DeliveryFailure = 'transient' | 'providerAuth' | 'invalidToken' | 'rejectedPayload' | 'unknown'
export interface DeliveryContext { notificationId: string; deliveryId: string; idempotencyKey: string; recipientKey: string; installationId: string; provider: string; deviceRegistrationId: string; payloadHash: string; createdAt: number; expiresAt: number; attempt: number; maxAttempts: number; nextAttemptAt: number | null; leaseOwner: string | null; leaseExpiresAt: number | null; apnsId: string; acceptedAt: number | null; sentAt: number | null; lastHttpStatus: number | null; lastReason: string | null; lastErrorClass: DeliveryFailure | null; mayHaveBeenWritten: boolean; correlationId: string | null; invocationSequence: number; providerTokenRefreshCount: number; ingestionStatus: 'pending' | 'durablyAcknowledged'; domainEventStatus: 'pending' | 'persisted'; effectStatus: 'pending' | 'persisted'; recipientStatus: 'pending' | 'targeted'; deliveryStatus: string; deliveryKey: string; now: number; authorityTransferCount: number; legacySenderPaused: boolean; reconciliationCheckpointConfirmed: boolean; deliveryAuthority: 'legacy' | 'outbox-v2'; decisionSyncStatus: 'pending' | 'acknowledged' | 'conflicted' | 'failed'; effectDispatchStatus: 'notDispatched' | 'pendingRecipient' | 'queued' | 'partiallyDispatched' | 'dispatched' | 'terminalFailure' }
export type DeliveryEvent =
  | { type: 'INGESTION_DURABLY_ACKNOWLEDGED' } | { type: 'POLICY_ALLOWED' } | { type: 'POLICY_SUPPRESSED' } | { type: 'QUIET_HOURS_ACTIVE'; nextEligibleAt: number } | { type: 'QUIET_HOURS_ENDED' }
  | { type: 'ACTIVE_TOKEN_FOUND' } | { type: 'NO_ACTIVE_TOKEN' } | { type: 'TOKEN_REGISTERED' } | { type: 'DISPATCH_DUE' }
  | { type: 'LEASE_ACQUIRED'; owner: string; expiresAt: number } | { type: 'CLOCK_TICK'; now: number } | { type: 'LEASE_LOST'; correlationId: string } | { type: 'PROVIDER_AUTH_READY'; correlationId: string } | { type: 'PROVIDER_AUTH_FAILED'; transient: boolean; correlationId: string }
  | { type: 'APNS_RESPONSE_RECEIVED'; status: number; reason?: string; apnsId?: string; acceptedAt?: number; retryAfter?: number; correlationId: string }
  | { type: 'TRANSPORT_FAILED_BEFORE_WRITE'; correlationId: string } | { type: 'TRANSPORT_OUTCOME_UNKNOWN'; correlationId: string } | { type: 'RETRY_DUE' } | { type: 'CREDENTIALS_ROTATED' }
  | { type: 'TOKEN_INVALIDATED' } | { type: 'EXPIRED' } | { type: 'CANCEL_REQUESTED' } | { type: 'LEGACY_SENDER_PAUSED' } | { type: 'RECONCILIATION_CHECKPOINT_CONFIRMED' } | { type: 'CUTOVER_REQUESTED' } | { type: 'CUTOVER_CONFIRMED' } | { type: 'ROLLBACK_TO_LEGACY_REQUESTED' }

export type ApnsClassification = 'accepted' | 'invalidToken' | 'rejectedPayload' | 'retry' | 'refreshAuth' | 'providerAuthBlocked' | 'unknownTerminal'
const invalidReasons = new Set(['BadDeviceToken', 'DeviceTokenNotForTopic', 'ExpiredToken', 'Unregistered'])
const rejectedReasons = new Set(['BadCollapseId', 'BadMessageId', 'BadTopic', 'BadPath', 'MethodNotAllowed', 'PayloadEmpty', 'PayloadTooLarge', 'BadPriority', 'BadExpirationDate', 'MissingTopic'])
export const classifyApnsResponse = (status: number, reason = ''): ApnsClassification => {
  if (status === 200) return 'accepted'
  if (invalidReasons.has(reason)) return 'invalidToken'
  if (reason === 'ExpiredProviderToken') return 'refreshAuth'
  if (reason === 'TooManyProviderTokenUpdates' || status === 403) return 'providerAuthBlocked'
  if (reason === 'IdleTimeout' || status === 429 || status === 500 || status === 503) return 'retry'
  if (rejectedReasons.has(reason) || status === 404 || status === 405 || status === 413) return 'rejectedPayload'
  return 'unknownTerminal'
}
export const effectIdentity = (domainEventId: string, effectType: string, schemaVersion: number) => `${domainEventId}:${effectType}:v${schemaVersion}`
export const recipientIdentity = (effectKey: string, participantId: string, channel: string) => `${effectKey}:${participantId}:${channel}`
export const deliveryIdentity = (recipientKey: string, installationId: string, provider: string) => `${recipientKey}:${installationId}:${provider}`
export type RecipientTargetState = { status: 'pendingTarget'; recipientKey: string; expiresAt: number } | { status: 'targeted'; recipientKey: string; expiresAt: number; installationIds: readonly string[] } | { status: 'expired'; recipientKey: string; expiresAt: number }
export const targetRecipient = (recipientKey: string, installationIds: readonly string[], expiresAt: number): RecipientTargetState => installationIds.length === 0
  ? { status: 'pendingTarget', recipientKey, expiresAt }
  : { status: 'targeted', recipientKey, expiresAt, installationIds: [...new Set(installationIds)] }
export const resumeRecipientTarget = (pending: RecipientTargetState, installationIds: readonly string[], now: number): RecipientTargetState =>
  now >= pending.expiresAt ? { status: 'expired', recipientKey: pending.recipientKey, expiresAt: pending.expiresAt } : targetRecipient(pending.recipientKey, installationIds, pending.expiresAt)
export const canRetry = (context: DeliveryContext, now: number) => context.attempt < context.maxAttempts && now < context.expiresAt
export const deliveryBackoff = (attempt: number, random = 0.5, retryAfter?: number) => retryAfter ?? Math.floor(Math.min(300_000, 1_000 * 2 ** Math.max(0, attempt - 1)) * Math.max(0, Math.min(1, random)))

export const notificationDeliveryMachine = setup({
  types: { context: {} as DeliveryContext, events: {} as DeliveryEvent, input: {} as Omit<DeliveryContext, 'attempt'|'nextAttemptAt'|'leaseOwner'|'leaseExpiresAt'|'acceptedAt'|'sentAt'|'lastHttpStatus'|'lastReason'|'lastErrorClass'|'mayHaveBeenWritten'> & Partial<DeliveryContext> },
  guards: {
    accepted: ({ event }) => event.type === 'APNS_RESPONSE_RECEIVED' && classifyApnsResponse(event.status, event.reason) === 'accepted', invalidToken: ({ event }) => event.type === 'APNS_RESPONSE_RECEIVED' && classifyApnsResponse(event.status, event.reason) === 'invalidToken', rejectedPayload: ({ event }) => event.type === 'APNS_RESPONSE_RECEIVED' && classifyApnsResponse(event.status, event.reason) === 'rejectedPayload', retryable: ({ event }) => event.type === 'APNS_RESPONSE_RECEIVED' && classifyApnsResponse(event.status, event.reason) === 'retry', refreshAuth: ({ event }) => event.type === 'APNS_RESPONSE_RECEIVED' && classifyApnsResponse(event.status, event.reason) === 'refreshAuth', authBlocked: ({ event }) => event.type === 'APNS_RESPONSE_RECEIVED' && classifyApnsResponse(event.status, event.reason) === 'providerAuthBlocked', retryBudgetAvailable: ({ context }) => canRetry(context, Date.now()), requestMayHaveBeenWritten: ({ context }) => context.mayHaveBeenWritten,
    correlated: ({ context, event }) => 'correlationId' in event && event.correlationId === context.correlationId,
    correlatedFirstExpiredProviderToken: ({ context, event }) => event.type === 'APNS_RESPONSE_RECEIVED' && event.correlationId === context.correlationId && classifyApnsResponse(event.status, event.reason) === 'refreshAuth' && context.providerTokenRefreshCount === 0,
    validLease: ({ context, event }) => event.type === 'LEASE_ACQUIRED' && event.owner.trim().length > 0 && event.expiresAt > context.now,
    authorityIsLegacy: ({ context }) => context.deliveryAuthority === 'legacy' && context.authorityTransferCount === 0,
    identityValid: ({ context }) => context.deliveryKey === deliveryIdentity(context.recipientKey, context.installationId, context.provider),
    cutoverReady: ({ context }) => context.deliveryAuthority === 'legacy' && context.legacySenderPaused && context.reconciliationCheckpointConfirmed && context.leaseOwner === null && context.attempt === 0 && context.authorityTransferCount === 0,
    rollbackSafe: ({ context }) => context.deliveryAuthority === 'outbox-v2' && context.leaseOwner === null && context.attempt === 0 && context.effectDispatchStatus === 'notDispatched',
    clockMovesForward: ({ context, event }) => event.type === 'CLOCK_TICK' && event.now >= context.now,
  },
  actions: {
    evaluatePolicy: () => {}, persistSuppressed: () => {}, persistDeferred: () => {}, persistAwaitingToken: () => {}, persistQueued: () => {}, acquireLease: () => {}, obtainProviderAuthentication: () => {}, sendToApns: () => {}, scheduleRetry: () => {}, openProviderAuthCircuit: () => {}, invalidateTargetInstallationOnly: () => {}, persistRejectedPayload: () => {}, persistTerminalOutcome: () => {},
    setQuietHours: assign({ nextAttemptAt: ({ event }) => event.type === 'QUIET_HOURS_ACTIVE' ? event.nextEligibleAt : null }),
    setLease: assign({ leaseOwner: ({ event }) => event.type === 'LEASE_ACQUIRED' ? event.owner : null, leaseExpiresAt: ({ event }) => event.type === 'LEASE_ACQUIRED' ? event.expiresAt : null }),
    clearLease: assign({ leaseOwner: null, leaseExpiresAt: null }),
    markSending: assign({ mayHaveBeenWritten: true }),
    markRetry: assign({ attempt: ({ context }) => context.attempt + 1, lastErrorClass: 'transient', acceptedAt: null, sentAt: null, mayHaveBeenWritten: false, nextAttemptAt: ({ context, event }) => event.type === 'APNS_RESPONSE_RECEIVED' ? (event.retryAfter ?? context.now + deliveryBackoff(context.attempt + 1)) : context.now + deliveryBackoff(context.attempt + 1) }),
    markUnknown: assign({ lastErrorClass: 'unknown', mayHaveBeenWritten: true, acceptedAt: null, sentAt: null }),
    captureResponse: assign({ lastHttpStatus: ({ event }) => event.type === 'APNS_RESPONSE_RECEIVED' ? event.status : null, lastReason: ({ event }) => event.type === 'APNS_RESPONSE_RECEIVED' ? event.reason ?? null : null }),
    markAccepted: assign({ acceptedAt: ({ event }) => event.type === 'APNS_RESPONSE_RECEIVED' ? event.acceptedAt ?? Date.now() : null, sentAt: ({ event }) => event.type === 'APNS_RESPONSE_RECEIVED' ? event.acceptedAt ?? Date.now() : null, apnsId: ({ context, event }) => event.type === 'APNS_RESPONSE_RECEIVED' ? event.apnsId ?? context.apnsId : context.apnsId }),
    beginInvocation: assign({ invocationSequence: ({ context }) => context.invocationSequence + 1, correlationId: ({ context }) => `delivery-${context.deliveryId}-${context.invocationSequence + 1}` }),
    incrementProviderTokenRefresh: assign({ providerTokenRefreshCount: ({ context }) => context.providerTokenRefreshCount + 1 }),
    setPolicyCheckStatus: assign({ deliveryStatus: 'policyCheck' }), setQueuedStatus: assign({ deliveryStatus: 'queued', effectDispatchStatus: 'queued' }), setAuthStatus: assign({ deliveryStatus: 'auth' }), setSendingStatus: assign({ deliveryStatus: 'sending' }),
    acknowledgeDurableIngestion: assign({ ingestionStatus: 'durablyAcknowledged', domainEventStatus: 'persisted', effectStatus: 'persisted', recipientStatus: 'targeted', decisionSyncStatus: 'acknowledged' }),
    setSuppressed: assign({ deliveryStatus: 'suppressed', effectDispatchStatus: 'terminalFailure' }), setDeferred: assign({ deliveryStatus: 'deferredQuietHours', effectDispatchStatus: 'pendingRecipient' }), setAwaiting: assign({ deliveryStatus: 'awaitingToken', effectDispatchStatus: 'pendingRecipient' }), setRetry: assign({ deliveryStatus: 'retry', effectDispatchStatus: 'queued' }), setUnknown: assign({ deliveryStatus: 'unknownOutcome', effectDispatchStatus: 'partiallyDispatched' }), setBlocked: assign({ deliveryStatus: 'providerAuthBlocked', effectDispatchStatus: 'queued' }), setAccepted: assign({ deliveryStatus: 'acceptedByAPNs', effectDispatchStatus: 'dispatched' }), setInvalid: assign({ deliveryStatus: 'invalidToken', effectDispatchStatus: 'terminalFailure' }), setRejected: assign({ deliveryStatus: 'rejectedPayload', effectDispatchStatus: 'terminalFailure' }), setExpired: assign({ deliveryStatus: 'expired', effectDispatchStatus: 'terminalFailure' }), setExhausted: assign({ deliveryStatus: 'retryExhausted', effectDispatchStatus: 'terminalFailure' }), setCancelled: assign({ deliveryStatus: 'cancelled', effectDispatchStatus: 'terminalFailure' }), setUnknownTerminal: assign({ deliveryStatus: 'unknownTerminal', effectDispatchStatus: 'terminalFailure' }),
    transferAuthority: assign({ deliveryAuthority: 'outbox-v2', authorityTransferCount: ({ context }) => context.authorityTransferCount + 1 }),
    pauseLegacySender: assign({ legacySenderPaused: true }), confirmCheckpoint: assign({ reconciliationCheckpointConfirmed: true }), advanceClock: assign({ now: ({ event }) => event.type === 'CLOCK_TICK' ? event.now : 0 }), rollbackAuthority: assign({ deliveryAuthority: 'legacy' }),
  },
}).createMachine({ id: 'notificationDelivery', initial: 'identityValidation', context: ({ input }) => ({ ...input, attempt: input.attempt ?? 0, nextAttemptAt: null, leaseOwner: null, leaseExpiresAt: null, acceptedAt: null, sentAt: null, lastHttpStatus: null, lastReason: null, lastErrorClass: null, mayHaveBeenWritten: false, correlationId: null, invocationSequence: 0, providerTokenRefreshCount: 0, ingestionStatus: 'pending', domainEventStatus: 'pending', effectStatus: 'pending', recipientStatus: 'pending', deliveryStatus: 'ingestion', deliveryKey: input.deliveryKey, now: input.now ?? 0, authorityTransferCount: 0, legacySenderPaused: false, reconciliationCheckpointConfirmed: false, deliveryAuthority: input.deliveryAuthority ?? 'outbox-v2', decisionSyncStatus: 'pending', effectDispatchStatus: 'notDispatched' }), on: { CLOCK_TICK: { guard: 'clockMovesForward', actions: 'advanceClock' }, ROLLBACK_TO_LEGACY_REQUESTED: { guard: 'rollbackSafe', actions: 'rollbackAuthority' } }, states: { identityValidation: { always: [{ guard: 'identityValid', target: 'ingestion' }, { target: 'identityMismatch' }] }, identityMismatch: { type: 'final', entry: 'setUnknownTerminal' },
  ingestion: { on: { INGESTION_DURABLY_ACKNOWLEDGED: { target: 'policyCheck', actions: 'acknowledgeDurableIngestion' }, CANCEL_REQUESTED: 'cancelled' } },
  policyCheck: { entry: ['setPolicyCheckStatus', 'evaluatePolicy'], on: { LEGACY_SENDER_PAUSED: { actions: 'pauseLegacySender' }, RECONCILIATION_CHECKPOINT_CONFIRMED: { actions: 'confirmCheckpoint' }, CUTOVER_REQUESTED: { guard: 'cutoverReady', target: 'authorityCutover' }, POLICY_SUPPRESSED: 'suppressed', QUIET_HOURS_ACTIVE: { target: 'deferredQuietHours', actions: 'setQuietHours' }, NO_ACTIVE_TOKEN: 'awaitingToken', POLICY_ALLOWED: 'queued', EXPIRED: 'expired' } },
  suppressed: { type: 'final', entry: ['setSuppressed', 'persistSuppressed'] },
  deferredQuietHours: { entry: ['setDeferred', 'persistDeferred'], on: { QUIET_HOURS_ENDED: 'policyCheck', EXPIRED: 'expired', CANCEL_REQUESTED: 'cancelled' } },
  awaitingToken: { entry: ['setAwaiting', 'persistAwaitingToken'], on: { TOKEN_REGISTERED: 'policyCheck', EXPIRED: 'expired', CANCEL_REQUESTED: 'cancelled' } },
  queued: { entry: ['setQueuedStatus', 'persistQueued'], on: { LEASE_ACQUIRED: { guard: 'validLease', target: 'auth', actions: 'setLease' }, EXPIRED: 'expired', CANCEL_REQUESTED: 'cancelled' } },
  auth: { entry: ['setAuthStatus', 'beginInvocation', 'obtainProviderAuthentication'], on: { PROVIDER_AUTH_READY: { guard: 'correlated', target: 'sending' }, PROVIDER_AUTH_FAILED: [{ guard: ({ context, event }) => event.correlationId === context.correlationId && event.transient, target: 'retry', actions: 'markRetry' }, { guard: 'correlated', target: 'providerAuthBlocked' }], LEASE_LOST: { guard: 'correlated', target: 'queued', actions: 'clearLease' }, EXPIRED: 'expired' } },
  sending: { entry: ['setSendingStatus', 'beginInvocation', 'sendToApns', 'markSending'], on: { APNS_RESPONSE_RECEIVED: [ { guard: ({ context, event }) => event.correlationId === context.correlationId && classifyApnsResponse(event.status, event.reason) === 'accepted', target: 'acceptedByAPNs', actions: ['captureResponse', 'markAccepted'] }, { guard: ({ context, event }) => event.correlationId === context.correlationId && classifyApnsResponse(event.status, event.reason) === 'invalidToken', target: 'invalidToken', actions: 'captureResponse' }, { guard: ({ context, event }) => event.correlationId === context.correlationId && classifyApnsResponse(event.status, event.reason) === 'rejectedPayload', target: 'rejectedPayload', actions: 'captureResponse' }, { guard: 'correlatedFirstExpiredProviderToken', target: 'auth', actions: ['captureResponse', 'incrementProviderTokenRefresh'] }, { guard: ({ context, event }) => event.correlationId === context.correlationId && classifyApnsResponse(event.status, event.reason) === 'refreshAuth', target: 'providerAuthBlocked', actions: 'captureResponse' }, { guard: ({ context, event }) => event.correlationId === context.correlationId && classifyApnsResponse(event.status, event.reason) === 'providerAuthBlocked', target: 'providerAuthBlocked', actions: 'captureResponse' }, { guard: ({ context, event }) => event.correlationId === context.correlationId && classifyApnsResponse(event.status, event.reason) === 'retry', target: 'retry', actions: ['captureResponse', 'markRetry'] }, { guard: 'correlated', target: 'unknownTerminal', actions: 'captureResponse' } ], TRANSPORT_FAILED_BEFORE_WRITE: { guard: 'correlated', target: 'retry', actions: 'markRetry' }, TRANSPORT_OUTCOME_UNKNOWN: { guard: 'correlated', target: 'unknownOutcome', actions: 'markUnknown' }, EXPIRED: 'unknownOutcome', CANCEL_REQUESTED: 'unknownOutcome' } },
  retry: { entry: ['setRetry', 'scheduleRetry'], on: { RETRY_DUE: [{ guard: 'retryBudgetAvailable', target: 'queued' }, { target: 'retryExhausted' }], EXPIRED: 'expired', CANCEL_REQUESTED: 'cancelled' } },
  unknownOutcome: { entry: 'setUnknown', on: { RETRY_DUE: [{ guard: 'retryBudgetAvailable', target: 'retry', actions: 'markRetry' }, { target: 'retryExhausted' }], APNS_RESPONSE_RECEIVED: { guard: ({ context, event }) => event.correlationId === context.correlationId && classifyApnsResponse(event.status, event.reason) === 'accepted', target: 'acceptedByAPNs', actions: ['captureResponse', 'markAccepted'] }, EXPIRED: 'expired', CANCEL_REQUESTED: 'cancelled' } },
  authorityCutover: { on: { CUTOVER_CONFIRMED: { target: 'policyCheck', actions: 'transferAuthority' }, ROLLBACK_TO_LEGACY_REQUESTED: 'policyCheck' } }, providerAuthBlocked: { entry: ['setBlocked', 'openProviderAuthCircuit'], on: { CREDENTIALS_ROTATED: 'auth', EXPIRED: 'expired', CANCEL_REQUESTED: 'cancelled' } },
  acceptedByAPNs: { type: 'final', entry: ['setAccepted', 'persistTerminalOutcome'] }, invalidToken: { type: 'final', entry: ['setInvalid', 'invalidateTargetInstallationOnly'] }, rejectedPayload: { type: 'final', entry: ['setRejected', 'persistRejectedPayload'] }, unknownTerminal: { type: 'final', entry: ['setUnknownTerminal', 'persistTerminalOutcome'] }, expired: { type: 'final', entry: ['setExpired', 'persistTerminalOutcome'] }, retryExhausted: { type: 'final', entry: ['setExhausted', 'persistTerminalOutcome'] }, cancelled: { type: 'final', entry: ['setCancelled', 'persistTerminalOutcome'] },
} })

export const deliveryInvariants = ['durable server ingestion acknowledgement is distinct from APNs acceptance', 'target-without-installation is a recipient state, never a delivery with a null device', 'provider outbox is server-only', 'one logical delivery per notification and installation', 'a valid lease prevents concurrent dispatch', 'sentAt and acceptedAt remain null before APNs HTTP 200', 'invalid token affects only the target installation', 'retry never exceeds expiration or budget', 'unknown outcome is never success', 'no transition depends on free text or an LLM'] as const
