package com.guyghost.wakeve.ui.equipment

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.outlined.Comment
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Cancel
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.CheckCircleOutline
import androidx.compose.material.icons.filled.Circle
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material.icons.filled.Inventory
import androidx.compose.material.icons.filled.Person
import androidx.compose.material.icons.filled.PersonAdd
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.AssistChip
import androidx.compose.material3.AssistChipDefaults
import androidx.compose.material3.Badge
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Checkbox
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FilterChip
import androidx.compose.material3.FloatingActionButton
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SuggestionChip
import androidx.compose.material3.SuggestionChipDefaults
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.guyghost.wakeve.comment.CommentRepository
import com.guyghost.wakeve.equipment.EquipmentManager
import com.guyghost.wakeve.equipment.EquipmentRepository
import com.guyghost.wakeve.models.CommentSection
import com.guyghost.wakeve.models.EquipmentCategory
import com.guyghost.wakeve.models.EquipmentChecklist
import com.guyghost.wakeve.models.EquipmentItem
import com.guyghost.wakeve.models.ItemStatus
import com.guyghost.wakeve.ui.activity.ParticipantInfo

/**
 * Equipment Checklist Screen
 *
 * Features:
 * - List equipment items grouped by category
 * - Filter by status
 * - Assign items to participants
 * - Update item status (checkboxes)
 * - Auto-generate checklist from event type
 * - Display statistics and progress
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun EquipmentChecklistScreen(
    eventId: String,
    participants: List<ParticipantInfo>,
    equipmentRepository: EquipmentRepository,
    commentRepository: CommentRepository,
    onNavigateBack: () -> Unit,
    onNavigateToComments: (eventId: String, section: CommentSection, sectionItemId: String?) -> Unit
) {
    var equipmentItems by remember { mutableStateOf<List<EquipmentItem>>(emptyList()) }
    var selectedStatus by remember { mutableStateOf<ItemStatus?>(null) }
    var showAddItemDialog by remember { mutableStateOf(false) }
    var showAutoGenerateDialog by remember { mutableStateOf(false) }
    var itemToEdit by remember { mutableStateOf<EquipmentItem?>(null) }
    var itemToDelete by remember { mutableStateOf<EquipmentItem?>(null) }
    var showAssignDialog by remember { mutableStateOf<EquipmentItem?>(null) }
    var stats by remember { mutableStateOf<EquipmentChecklist?>(null) }
    var commentCount by remember { mutableIntStateOf(0) }

    // Load data
    fun loadData() {
        equipmentItems = equipmentRepository.getEquipmentItemsByEventId(eventId)
        stats = equipmentRepository.getEquipmentChecklist(eventId)
        commentCount = commentRepository.countCommentsBySection(eventId, CommentSection.EQUIPMENT).toInt()
    }

    LaunchedEffect(eventId) {
        loadData()
    }

    // Filter items
    val filteredItems = equipmentItems.filter { item ->
        selectedStatus == null || item.status == selectedStatus
    }

    // Group by category
    val itemsByCategory = filteredItems.groupBy { it.category }
        .toList()
        .sortedBy { it.first.ordinal }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(equipmentScreenTitle()) },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, equipmentBackContentDescription())
                    }
                },
                actions = {
                    // Auto-generate button
                    IconButton(onClick = { showAutoGenerateDialog = true }) {
                        Icon(Icons.Default.AutoAwesome, equipmentAutoGenerateContentDescription())
                    }

                    // Comments icon with badge
                    IconButton(onClick = {
                        onNavigateToComments(eventId, CommentSection.EQUIPMENT, null)
                    }) {
                        Box {
                            Icon(
                                Icons.AutoMirrored.Outlined.Comment,
                                contentDescription = equipmentCommentContentDescription(commentCount)
                            )
                            if (commentCount > 0) {
                                Box(
                                    modifier = Modifier
                                        .size(16.dp)
                                        .background(
                                            color = MaterialTheme.colorScheme.error,
                                            shape = CircleShape
                                        )
                                        .align(Alignment.TopEnd),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Text(
                                        text = commentCount.toString(),
                                        style = MaterialTheme.typography.labelSmall,
                                        color = MaterialTheme.colorScheme.onError,
                                        fontWeight = FontWeight.Bold
                                    )
                                }
                            }
                        }
                    }
                }
            )
        },
        floatingActionButton = {
            FloatingActionButton(
                onClick = { showAddItemDialog = true }
            ) {
                Icon(Icons.Default.Add, equipmentAddContentDescription())
            }
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
        ) {
            // Statistics Card
            stats?.let { checklistStats ->
                EquipmentStatsCard(
                    stats = checklistStats,
                    participantCount = participants.size,
                    modifier = Modifier.padding(16.dp)
                )
            }

            // Filter Chips
            LazyRow(
                modifier = Modifier.padding(horizontal = 16.dp),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                item {
                    FilterChip(
                        selected = selectedStatus == null,
                        onClick = { selectedStatus = null },
                        label = { Text(equipmentAllStatusesLabel()) }
                    )
                }

                ItemStatus.entries.forEach { status ->
                    item {
                        FilterChip(
                            selected = selectedStatus == status,
                            onClick = {
                                selectedStatus = if (selectedStatus == status) null else status
                            },
                            label = { Text(equipmentStatusLabel(status)) },
                            leadingIcon = {
                                Icon(
                                    imageVector = when (status) {
                                        ItemStatus.NEEDED -> Icons.Default.Circle
                                        ItemStatus.ASSIGNED -> Icons.Default.Person
                                        ItemStatus.CONFIRMED -> Icons.Default.CheckCircle
                                        ItemStatus.PACKED -> Icons.Default.CheckCircleOutline
                                        ItemStatus.CANCELLED -> Icons.Default.Cancel
                                    },
                                    contentDescription = null,
                                    modifier = Modifier.size(16.dp)
                                )
                            }
                        )
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Equipment List by Category
            if (filteredItems.isEmpty()) {
                EmptyStateCard(
                    message = if (equipmentItems.isEmpty())
                        equipmentEmptyListMessage()
                    else
                        equipmentEmptyFilteredMessage(),
                    actionLabel = if (equipmentItems.isEmpty()) equipmentPrepareListActionLabel() else null,
                    onActionClick = if (equipmentItems.isEmpty()) {
                        { showAutoGenerateDialog = true }
                    } else {
                        null
                    },
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(16.dp)
                )
            } else {
                LazyColumn(
                    contentPadding = PaddingValues(16.dp),
                    verticalArrangement = Arrangement.spacedBy(16.dp)
                ) {
                    itemsByCategory.forEach { (category, items) ->
                        item {
                            CategorySection(
                                category = category,
                                items = items,
                                participants = participants,
                                onItemClick = { item -> itemToEdit = item },
                                onAssignClick = { item -> showAssignDialog = item },
                                onStatusChange = { item, newStatus ->
                                    val updated = item.copy(status = newStatus)
                                    equipmentRepository.updateEquipmentItem(updated)
                                    loadData()
                                },
                                onDeleteClick = { item -> itemToDelete = item }
                            )
                        }
                    }
                }
            }
        }
    }

    // Dialogs
    if (showAddItemDialog) {
        AddEditItemDialog(
            item = null,
            participants = participants,
            onDismiss = { showAddItemDialog = false },
            onConfirm = { item ->
                equipmentRepository.createEquipmentItem(item.copy(eventId = eventId))
                showAddItemDialog = false
                loadData()
            }
        )
    }

    itemToEdit?.let { item ->
        AddEditItemDialog(
            item = item,
            participants = participants,
            onDismiss = { itemToEdit = null },
            onConfirm = { updated ->
                equipmentRepository.updateEquipmentItem(updated)
                itemToEdit = null
                loadData()
            }
        )
    }

    showAssignDialog?.let { item ->
        AssignItemDialog(
            item = item,
            participants = participants,
            onDismiss = { showAssignDialog = null },
            onConfirm = { participantId ->
                val updated = item.copy(
                    assignedTo = participantId,
                    status = if (participantId != null) ItemStatus.ASSIGNED else ItemStatus.NEEDED
                )
                equipmentRepository.updateEquipmentItem(updated)
                showAssignDialog = null
                loadData()
            }
        )
    }

    if (showAutoGenerateDialog) {
        AutoGenerateDialog(
            onDismiss = { showAutoGenerateDialog = false },
            onConfirm = { eventType ->
                val generated = EquipmentManager.createChecklist(
                    eventId = eventId,
                    eventType = eventType
                )
                generated.forEach { item: EquipmentItem ->
                    equipmentRepository.createEquipmentItem(item)
                }
                showAutoGenerateDialog = false
                loadData()
            }
        )
    }

    itemToDelete?.let { item ->
        AlertDialog(
            onDismissRequest = { itemToDelete = null },
            title = { Text(equipmentDeleteItemTitle()) },
            text = { Text(equipmentDeleteItemMessage(item.name)) },
            confirmButton = {
                TextButton(onClick = {
                    equipmentRepository.deleteEquipmentItem(item.id)
                    itemToDelete = null
                    loadData()
                }) {
                    Text(equipmentDeleteActionLabel(), color = MaterialTheme.colorScheme.error)
                }
            },
            dismissButton = {
                TextButton(onClick = { itemToDelete = null }) {
                    Text(equipmentCancelActionLabel())
                }
            }
        )
    }
}

@Composable
private fun EquipmentStatsCard(
    stats: EquipmentChecklist,
    participantCount: Int,
    modifier: Modifier = Modifier
) {
    val sharedCostPerPerson = if (participantCount > 0) stats.totalCost / participantCount else 0L

    Card(
        modifier = modifier.fillMaxWidth(),
        elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
    ) {
        Column(
            modifier = Modifier.padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            Text(
                text = equipmentProgressTitle(),
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
            )

            // Progress Bar
            val progress = if (stats.totalItems > 0)
                stats.packedItems.toFloat() / stats.totalItems
            else
                0f

            Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                LinearProgressIndicator(
                    progress = { progress },
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(8.dp),
                )

                Text(
                    text = equipmentProgressLabel(stats.packedItems, stats.totalItems, (progress * 100).toInt()),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }

            // Status Summary
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Column {
                    Text(
                        text = (stats.totalItems - stats.assignedItems - stats.confirmedItems - stats.packedItems).toString(),
                        style = MaterialTheme.typography.titleLarge,
                        fontWeight = FontWeight.Bold
                    )
                    Text(
                        text = equipmentStatusLabel(ItemStatus.NEEDED),
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }

                Column {
                    Text(
                        text = stats.assignedItems.toString(),
                        style = MaterialTheme.typography.titleLarge,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.primary
                    )
                    Text(
                        text = equipmentAssignedSummaryLabel(),
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }

                Column {
                    Text(
                        text = stats.confirmedItems.toString(),
                        style = MaterialTheme.typography.titleLarge,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.tertiary
                    )
                    Text(
                        text = equipmentConfirmedSummaryLabel(),
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }

            HorizontalDivider()

            // Cost Summary
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Column {
                    Text(
                        text = equipmentTotalCostLabel(),
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Text(
                        text = "${stats.totalCost / 100}€",
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Bold
                    )
                }

                Column(horizontalAlignment = Alignment.End) {
                    Text(
                        text = equipmentPerPersonLabel(),
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Text(
                        text = "${sharedCostPerPerson / 100}€",
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.primary
                    )
                }
            }
        }
    }
}

@Composable
private fun CategorySection(
    category: EquipmentCategory,
    items: List<EquipmentItem>,
    participants: List<ParticipantInfo>,
    onItemClick: (EquipmentItem) -> Unit,
    onAssignClick: (EquipmentItem) -> Unit,
    onStatusChange: (EquipmentItem, ItemStatus) -> Unit,
    onDeleteClick: (EquipmentItem) -> Unit
) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = equipmentCategoryLabel(category),
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold
                )

                Badge {
                    Text(items.size.toString())
                }
            }

            Spacer(modifier = Modifier.height(12.dp))

            items.forEach { item ->
                EquipmentItemRow(
                    item = item,
                    participants = participants,
                    onClick = { onItemClick(item) },
                    onAssignClick = { onAssignClick(item) },
                    onStatusChange = { newStatus -> onStatusChange(item, newStatus) },
                    onDeleteClick = { onDeleteClick(item) }
                )

                if (item != items.last()) {
                    HorizontalDivider(modifier = Modifier.padding(vertical = 8.dp))
                }
            }
        }
    }
}

@Composable
private fun EquipmentItemRow(
    item: EquipmentItem,
    participants: List<ParticipantInfo>,
    onClick: () -> Unit,
    onAssignClick: () -> Unit,
    onStatusChange: (ItemStatus) -> Unit,
    onDeleteClick: () -> Unit
) {
    var expanded by remember { mutableStateOf(false) }

    Column {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .clickable { expanded = !expanded },
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Text(
                        text = item.name,
                        style = MaterialTheme.typography.bodyLarge,
                        fontWeight = FontWeight.Medium
                    )

                    if (item.quantity > 1) {
                        Text(
                            text = " × ${item.quantity}",
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }

                item.notes?.let { notes ->
                    if (notes.isNotBlank()) {
                        Text(
                            text = notes,
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }

                Row(
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    // Status Badge
                    StatusBadge(status = item.status)

                    // Assigned Person
                    item.assignedTo?.let { participantId ->
                        val participant = participants.find { it.id == participantId }
                        participant?.let {
                            AssistChip(
                                onClick = onAssignClick,
                                label = { Text(it.name, style = MaterialTheme.typography.labelSmall) },
                                leadingIcon = {
                                    Icon(
                                        Icons.Default.Person,
                                        contentDescription = null,
                                        modifier = Modifier.size(16.dp)
                                    )
                                }
                            )
                        }
                    } ?: run {
                        AssistChip(
                            onClick = onAssignClick,
                            label = { Text(equipmentAssignActionLabel(), style = MaterialTheme.typography.labelSmall) },
                            leadingIcon = {
                                Icon(
                                    Icons.Default.PersonAdd,
                                    contentDescription = null,
                                    modifier = Modifier.size(16.dp)
                                )
                            }
                        )
                    }

                    // Cost
                    item.sharedCost?.let { cost ->
                        if (cost > 0) {
                            Text(
                                text = "${cost / 100}€",
                                style = MaterialTheme.typography.labelMedium,
                                color = MaterialTheme.colorScheme.primary
                            )
                        }
                    }
                }
            }

            // Status Checkbox
            Checkbox(
                checked = item.status == ItemStatus.PACKED,
                onCheckedChange = { checked ->
                    val newStatus = if (checked) ItemStatus.PACKED else {
                        if (item.assignedTo != null) ItemStatus.CONFIRMED else ItemStatus.NEEDED
                    }
                    onStatusChange(newStatus)
                }
            )
        }

        // Expanded Actions
        if (expanded) {
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 8.dp),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                AssistChip(
                    onClick = onClick,
                    label = { Text(equipmentEditActionLabel()) },
                    leadingIcon = {
                        Icon(Icons.Default.Edit, null, modifier = Modifier.size(16.dp))
                    }
                )

                AssistChip(
                    onClick = onDeleteClick,
                    label = { Text(equipmentDeleteActionLabel()) },
                    leadingIcon = {
                        Icon(Icons.Default.Delete, null, modifier = Modifier.size(16.dp))
                    },
                    colors = AssistChipDefaults.assistChipColors(
                        labelColor = MaterialTheme.colorScheme.error
                    )
                )
            }
        }
    }
}

@Composable
private fun StatusBadge(status: ItemStatus) {
    val (color, label) = when (status) {
        ItemStatus.NEEDED -> MaterialTheme.colorScheme.outline to equipmentStatusLabel(ItemStatus.NEEDED)
        ItemStatus.ASSIGNED -> MaterialTheme.colorScheme.primary to equipmentStatusLabel(ItemStatus.ASSIGNED)
        ItemStatus.CONFIRMED -> MaterialTheme.colorScheme.tertiary to equipmentStatusLabel(ItemStatus.CONFIRMED)
        ItemStatus.PACKED -> MaterialTheme.colorScheme.secondary to equipmentStatusLabel(ItemStatus.PACKED)
        ItemStatus.CANCELLED -> MaterialTheme.colorScheme.error to equipmentStatusLabel(ItemStatus.CANCELLED)
    }

    SuggestionChip(
        onClick = {},
        label = { Text(label, style = MaterialTheme.typography.labelSmall) },
        colors = SuggestionChipDefaults.suggestionChipColors(
            containerColor = color.copy(alpha = 0.1f),
            labelColor = color
        )
    )
}

@Composable
private fun EmptyStateCard(
    message: String,
    actionLabel: String? = null,
    onActionClick: (() -> Unit)? = null,
    modifier: Modifier = Modifier
) {
    Card(
        modifier = modifier,
        elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(32.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Icon(
                imageVector = Icons.Default.Inventory,
                contentDescription = null,
                modifier = Modifier.size(64.dp),
                tint = MaterialTheme.colorScheme.onSurfaceVariant
            )

            Text(
                text = message,
                style = MaterialTheme.typography.bodyLarge,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )

            if (actionLabel != null && onActionClick != null) {
                Button(onClick = onActionClick) {
                    Text(actionLabel)
                }
            }
        }
    }
}

internal fun equipmentScreenTitle(): String = "Liste d'équipement"

internal fun equipmentBackContentDescription(): String = "Retour"

internal fun equipmentAutoGenerateContentDescription(): String = "Préparer automatiquement une liste d'équipement"

internal fun equipmentCommentContentDescription(commentCount: Int): String =
    if (commentCount <= 0) "Aucun commentaire équipement" else "$commentCount commentaire${if (commentCount > 1) "s" else ""} équipement"

internal fun equipmentAddContentDescription(): String = "Ajouter un équipement"

internal fun equipmentAllStatusesLabel(): String = "Tous"

internal fun equipmentEmptyListMessage(): String = "Aucun équipement ajouté"

internal fun equipmentEmptyFilteredMessage(): String = "Aucun équipement avec ce statut"

internal fun equipmentPrepareListActionLabel(): String = "Préparer une liste"

internal fun equipmentDeleteItemTitle(): String = "Supprimer l'équipement ?"

internal fun equipmentDeleteItemMessage(itemName: String): String =
    "Supprimer « $itemName » de la liste d'équipement ?"

internal fun equipmentDeleteActionLabel(): String = "Supprimer"

internal fun equipmentProgressTitle(): String = "Progression"

internal fun equipmentProgressLabel(packedItems: Int, totalItems: Int, percent: Int): String =
    "$packedItems / $totalItems équipements prêts ($percent%)"

internal fun equipmentAssignedSummaryLabel(): String = "Assignés"

internal fun equipmentConfirmedSummaryLabel(): String = "Confirmés"

internal fun equipmentTotalCostLabel(): String = "Coût total"

internal fun equipmentPerPersonLabel(): String = "Par personne"

internal fun equipmentAssignActionLabel(): String = "Assigner"

internal fun equipmentEditActionLabel(): String = "Modifier"
